### ISSUE TITLE
how loadMap from xml works?

### ISSUE THREAD

**Issue by am2222** [mapnik/mapnik-support#102]
Hi,
I have an xml file which only includes a set of styles, If I add some styles using c++ api and then I load xml file does it overwrite previously added styles? and also can I add layers again using api functions and use the styles which are loaded from xml?
thanks

**Comment by talaj** [comment]
> If I add some styles using c++ api and then I load xml file does it overwrite previously added styles?

No, it will add them as new styles and it will throw an error in case of style name collision.

> and also can I add layers again using api functions and use the styles which are loaded from xml?

Yes, this is possible. You can load an XML style without layer definitions and add them later by the Mapnik C++ API.

**Comment by am2222** [comment]
@talaj  thanks for your answer, So in fact each time we load a new style.xml we just add those styles to the old ones . it does not clear previous styles, right?

**Comment by talaj** [comment]
Yes, it does not clear previous styles.

**Comment by am2222** [comment]
@talaj  thanks very much for your answer
