### ISSUE TITLE
Cloning v3.0.18

### ISSUE THREAD

**Issue by dashwonders** [mapnik/mapnik-support#104]
Good afternoon mapnik-support,

This is neither a bug or issue.  I am new to using git and mapnik, and I have an elementary question:
How do I clone mapnik 3.0.18 instead of the master branch?
The instructions I am following are:

_git clone https://github.com/mapnik/mapnik.git --depth 10
cd mapnik
git submodule update --init
git submodule update --init deps/mapbox/variant
bash
source bootstrap.sh
./configure && make
make test
sudo make install_

I realized, however, this is compiling mapnik 3.1.0 causing errors owing to dependencies.   Following recommendation in issue #100 by @springmeyer, I would like to get either v3.0.17 or preferably v3.0.18 instead of the master branch.   Any help would be greatly appreciated.  Thank you.

**Comment by talaj** [comment]
I think that the processes is basically right. If you don't want to develop Mapnik, don't use the bootstrap thing. Its only purpose is to make environment under which all visual tests are passing.

This should work well:

```console
git clone
git submodule update --init
./configure && make
```

If you want to use some release version like [v3.0.18](https://github.com/mapnik/mapnik/tree/v3.0.18), just checkout the corresponding git tag. If you want the latest Mapnik from 3.0.x series, there is a branch [v3.0.x](https://github.com/mapnik/mapnik/tree/v3.0.x).

**Comment by flippmoke** [comment]
@dashwonders you will need to check out the right branch

```
git checkout v3.0.x
```
This is the current development branch of the `v3.0.x` series. 

You can also check out a specific tag this same way. A tag is how we mark released versions.

```
git checkout v3.0.18
```
