### ISSUE TITLE
Building mapnik+node-mapnik with postgis SSL support

### ISSUE THREAD

**Issue by tomalrussell** [mapnik/mapnik-support#110]
When trying to connect to Postgres with sslmode=require, I get:
```
Error: Postgis Plugin: sslmode value "require" invalid when SSL support is not compiled in
```

Related to https://github.com/mapnik/node-mapnik/issues/755 and https://github.com/mapnik/mapnik/issues/2550, but I'm not on Heroku (so the pgbouncer fix doesn't seem to be relevant), and I'm working with Ubuntu 18.04 (so the mapnik nightly builds don't seem to be available).

My steps so far:
- clone https://github.com/mapnik/mapnik, checkout v3.0.20
- follow https://github.com/mapnik/mapnik/wiki/UbuntuInstallation#ubuntu-1604 to build
- I can then run `mapnik-config -v` and get `3.0.20`
- clone https://github.com/mapnik/node-mapnik, checkout v3.0.x
- following https://github.com/mapnik/node-mapnik#source-build (option B) - `make release_base`
- `npm pack` > produces `mapnik-3.7.3-svg1.tgz`
- in a test project, npm install `path/to/mapnik-3.7.3-svg1.tgz`

Is there anything obvious I'm missing, or more information that I can provide?

**Comment by talaj** [comment]
The error message comes from https://github.com/postgres/postgres/blob/e3f99e03e2ec65e7ddb1f3056b545f2afa57b2d0/src/interfaces/libpq/fe-connect.c#L1161

It's a block within `#ifndef USE_SSL`, which means your libpq was compiled without `USE_SSL`.

**Comment by lightmare** [comment]
It's not "your libpq" that's the culprit, it's libpq from mason installed by `./bootstrap.sh`.

You should be able to compile mapnik with just system packages, I'd start with
```sh
# add-apt-repository ppa:ubuntugis/ppa
# apt-get update
apt-get -s build-dep mapnik
```
to see what's missing, some may be optional.
`rm mapnik-settings.env config.py #`, to clear stuff from bootstrap;

`./configure #`, install what's missing, repeat until satisfied

**Comment by tomalrussell** [comment]
Thanks for the quick responses - I'll have a go at installing with system packages and update with a :+1: or more questions.

**Comment by tomalrussell** [comment]
Okay, compiling with system packages seems to work. 

Here are my steps (script in details below):

1. install dependences (see https://github.com/mapnik/mapnik/blob/master/INSTALL.md)
1. build node with shared openssl option (node v8.11.3 would bundle openssl 1.0, whereas Ubuntu 18.04 libpq-dev links against openssl 1.1)
1. build mapnik
1. build node-mapnik straight into a project with `npm install --build-from-source=mapnik`
1. test creating a postgis Datasource with `PGSSLMODE=require` environment variable set

I learnt that node bundles openssl, and compiling node with `./configure --shared-openssl` fixed a segmentation fault that was being thrown (when running my test script with `node index.js`) when I had just installed the linux binaries.

- `whereis libpq` to find libpq
- `ldd /usr/lib/x86_64-linux-gnu/libpq.so | grep ssl` to check libpq ssl version
- `node -e 'console.log(process.versions.openssl)'` to check node ssl version

Note that this was for Ubuntu 18.04. Almost the same steps worked on Ubuntu 16.04, though the default boost libraries are only recent enough for mapnik v3.0.x, and libpq was happy with the version of openssl packaged in the node binaries (so compiling node wasn't necessary).

<details>
<summary>Script</summary>

```bash
# Set up build environment
sudo add-apt-repository universe  # provides libboost-regex-dev, libboost-python-dev, libgdal-dev, postgis
sudo apt update
sudo apt upgrade
sudo apt install --no-install-recommends \
    build-essential clang python python-dev \
    libicu-dev \
    zlib1g-dev \
    libharfbuzz-dev \
    libfreetype6 libfreetype6-dev \
    libxml2 libxml2-dev \
    libpng-dev libjpeg-dev \
    postgresql libpq-dev \
    postgresql-10-postgis-2.4 postgresql-10-postgis-2.4-scripts # or postgresql-9.5-postgis-2.2 (on Ubuntu 16.04) \
    libgdal-dev libproj-dev \
    libboost-filesystem-dev \
    libboost-system-dev \
    libboost-regex-dev \
    libboost-program-options-dev \
    libboost-python-dev \
    libboost-thread-dev \
    libssl-dev  # for node to compile against

# Node with shared openssl (would bundle 1.0, system libpq links against 1.1)
NODE_VERSION=v8.11.3
wget https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION.tar.gz
tar xf node-$NODE_VERSION.tar.gz
cd node-$NODE_VERSION
./configure --shared-openssl
make -j4

cat >> ~/.profile <<EOF
export NODEJS_HOME=/usr/local/lib/nodejs/node-$NODE_VERSION/bin
export PATH=\$NODEJS_HOME:\$PATH
EOF
. ~/.profile

# Build mapnik
cd ~
git clone https://github.com/mapnik/mapnik.git
cd mapnik 
git checkout 434511c  # commit id referenced by node-mapnik/package.json->mapnik_version
# git checkout v3.0.x  # would work with node-mapnik 3.7.2
git submodule update --init
rm config.py
./configure
JOBS=4 make
sudo make install

# Check
mapnik-config -v

# Test
cd ~
mkdir test-project
cd test-project

sudo -S -u postgres psql -c 'create role tom with superuser login;'
createdb test
psql -c "create user test with login password 'test';" -d test
psql -c 'grant all on database test to test;' -d test
psql -c 'create extension postgis;' -d test
psql -c 'create table test( geom geometry(geometry, 3857) );' -d test -U test

cat > package.json <<EOF
{
    "dependencies": {
        "mapnik": "^4.0.0"  
    }
}
EOF
# note: node-mapnik version "^3.7.2" works against mapnik v3.0.x branch

npm i --build-from-source=mapnik

cat > index.js <<EOF
const mapnik = require('mapnik')

console.log(process.env.PGSSLMODE)

mapnik.register_default_input_plugins()

new mapnik.Datasource({
    'type': 'postgis',
    'host': 'localhost',
    'dbname': 'test',
    'user': 'test',
    'password': 'test',
    'port': 5432,
    'table': 'test',
    'geometry_field': 'geom',
    'extent': '-20005048,-9039211,19907487,17096598'
})
EOF

node index.js
PGSSLMODE=require node index.js
```

</details>
