### ISSUE TITLE
Line Pattern Symbolizer Spacing

### ISSUE THREAD

**Issue by kevinzg** [mapnik/mapnik-support#111]
How can I add spacing between the repeated symbols of the Line Pattern Symbolizer?

I've looked at [this reference](https://github.com/mapnik/mapnik-reference/blob/gh-pages/3.0.20/reference.json#L1517) and [the wiki](https://github.com/mapnik/mapnik/wiki/LinePatternSymbolizer) but that option seems to be missing. Is there any other way?

**Comment by talaj** [comment]
If you want to repeat a symbol along a line, I would recommend MarkersSymbolizer or ShieldSymbolizer. In addition to documentation you referenced, a good source of information can be visual tests. Take a look on [marker-direction.xml](https://github.com/mapnik/test-data-visual/blob/master/styles/marker-direction.xml) tests:

![marker-direction.xml](https://raw.githubusercontent.com/mapnik/test-data-visual/master/images/marker-direction-1152-384-1.0-agg-reference.png)


LinePatternSymbolizer is meant primarily for continuous pattern, but support for dashed lines was added recently in https://github.com/mapnik/mapnik/pull/3980:
![line-pattern-repeat-on-line-dasharray.xml](https://raw.githubusercontent.com/mapnik/test-data-visual/master/images/line-pattern-repeat-on-line-dasharray-800-800-1.0-agg-reference.png)

**Comment by kevinzg** [comment]
That's exactly what I need, thank you.
