### ISSUE TITLE
Cut labels even with big buffer-size

### ISSUE THREAD

**Issue by zdila** [mapnik/mapnik-support#113]
Hello,

I am using mapnik 3.0.20 and have problem with cut text:

![image](https://user-images.githubusercontent.com/636095/47969073-b0172300-e072-11e8-98a4-9e46dcefb58d.png)

I've set buffer-size even to 1024 on `Map` and `Layer` but the text is still cut.

```
<Map background-color="white" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over" buffer-size="1024">
  <Style name="infopoints">
    <Rule>
      <Filter>[type] = 'guidepost'</Filter>
      <MaxScaleDenominator>200000</MaxScaleDenominator>
      <TextSymbolizer size="10" face-name="DejaVu Sans Book" fill="black" halo-fill="white" halo-radius="1" dy="-8" wrap-width="80" wrap-before="true">[name] + '\n' + [ele]</TextSymbolizer>
    </Rule>
  </Style>

  <Layer buffer-size="1024">
    <StyleName>infopoints</StyleName>
    <Datasource base="db">
      <Parameter name="table">(select name, ele, type, geometry from import.osm_infopoints order by osm_id) as foo</Parameter>
    </Datasource>
  </Layer>
</Map>
```

Am I doing something wrong?

PS: I don't want to use `avoid-edges` property as it elemitinates too many labels.

**Comment by talaj** [comment]
Ahoj!

I would say that those labels does not collide deterministically. Try to sort the datasource result by id, for example. Order of rows returned from a PostgreSQL command is undefined without sorting.

**Comment by zdila** [comment]
Hi @talaj. Thanks for your answer. You can see in the SQL that I am already sorting it by `osm_id`.

**Comment by zdila** [comment]
I found a fix to my problem - I had to provide `{ buffer_size: 256 }` to options of `map.render` nodejs function (OK, I forgot to mention that I use nodejs). But does it mean that if nodejs is used then `buffer-size` attribute of the `Map` is ignored?

**Comment by talaj** [comment]
Oh, sorry for my blindness.

It seems like a bug. Buffer-size zero is passed [here](https://github.com/mapnik/node-mapnik/blob/94681bcf3aba66f47b08c1fa8199d552ca796dc4/src/mapnik_map.cpp#L2688) by default. Collision detector with zero buffer is then created [here](https://github.com/mapnik/mapnik/blob/7dcf5ee0826e41f3c4ae378dd094ad7942fb435d/src/renderer_common.cpp#L86-L88).

**Comment by zdila** [comment]
Thanks for the analysis. Should I report it to `mapnik/mapnik` issues or is this report sufficient?

**Comment by talaj** [comment]
It would be great if you can report it in [node-mapnik](https://github.com/mapnik/node-mapnik).

**Comment by talaj** [comment]
It seems to be intentional: https://github.com/mapnik/node-mapnik/issues/342. In this case the only thing to do is to emphasize it in the documentation.
