### ISSUE TITLE
error: Failed to parse attribute 'placement'. Expected one of [point, line, vertex, interior] but got 'point' in style 'MyStyle' in TextSymbolizer at line 12

### ISSUE THREAD

**Issue by wibrahim** [mapnik/mapnik-support#12]
Built mapnik for iOS 6.1 from <a href="https://github.com/PaulWagener/mapnik-ios-framework">mapnik-ios-framework</a> 
On MacOSx 10.8.3 with XCode 4.6.2 

Mapnik was built using clang++ compiler:

``` bash
$ clang --version
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin12.3.0
Thread model: posix
```

with Cairo and ICU support.

My Style.xml file:

``` xml
 <Style name="MyStyle">
        <Rule>
            <TextSymbolizer face-name="DejaVu Sans Book" size="5" fill="black" placement="point">[NAME]</TextSymbolizer>
        </Rule>
    </Style>
```

**Comment by springmeyer** [comment]
@wibrahim - this error can happen when two c++ libraries are both involved/linked. I've seen it on solaris, for example, when some mapnik dependencies are compiled with suncc while mapnik is compiled with gcc. I've also seen it with early clang++ incompatibility with g++ on OSX (though now you can share binaries between clang/gcc as long as they both link to libstdc++ or libc++, but not both).

**Comment by wibrahim** [comment]
@springmeyer  probably that's what I am facing, I know that boost libraries were built using libstdc++ and in my xcode project the compiler setting is using libc++ and when I set it to libstd++ I get all different type of errors. I will try to unify my build settings/environment for all the dependencies and see if that will solve the problem. Thanks for the info.

**Comment by springmeyer** [comment]
We are working on a mapnik branch that more fully supports libc++/c++11. At this time I've only tried/successfully built mapnik for ios using libstdc++ only.

**Comment by wibrahim** [comment]
@springmeyer thanks for the tip, I was actually able to build mapnik and all dependencies using libstdc++/clang++ and that eliminated this error but when trying to load an image within the ShieldSymbolizer I get this error msg:

```
"Mapnik LOG> 2013-04-25 15:43:36:"  could not intialize reader for: '/Library/Application Support/iPhone Simulator/6.1/Applications/548F1A4F-6389-4D94-8396-7C8A6CF73CC5/MapnikTest.app/CountryPoint.png'
```

My Style looks like:

``` xml
<Style name="MyStyle">
    <Rule>
        <ShieldSymbolizer file="images/CountryPoint.png" face-name="DejaVu Sans Book" size="2" fill="#000000" spacing="100" transform="scale(2.0,2.0)" placement="point">[NAME]</ShieldSymbolizer>
    </Rule>
</Style>
```

Thanks for your help.

**Comment by springmeyer** [comment]
@wibrahim - yep libstdc++/clang++ work well. As far as png loading, there are two things that will break it. 1) you need to tell xcode not to reformat your PNG's when they are copied to the device. You can do this by putting `COMPRESS_PNG_FILES = NO` in your xcconfig or editing your project settings. 2) Mapnik uses a system for registering specific image format support at runtime that breaks when using Mapnik as a static library, see https://github.com/mapnik/mapnik/issues/811

**Comment by wibrahim** [comment]
Thanks for the info again. The two steps solved my problem and now I am able to load png files with a ShieldSymbolizer.

**Comment by wibrahim** [comment]
@springmeyer After playing with mapnik loading various shapefiles I tried to change my datasource to use sqlite, cause I wanted to add some geometry constraints to the label placements, which I do not think is doable using shapefiles. 
So I rebuilt mapnik with sqlite support for plugins, I enabled the PLUGIN_LINIKING='static' and got the sqlite.input inside the lib/mapnik/input directory, now when I try to load an sqlite database I get this error:

```
error: Shape Plugin: shapefile 'Library/Application Support/iPhone Simulator/6.1/Applications/E628F20A-FFAD-4712-A1B2-65E89E33F7A1/MB Example.app/qgis_spatiallite.sqlite.shp' does not exist  encountered during parsing of layer 'point' in Layer at line 50
```

My xml datasource part is:

``` xml
<Layer name="point" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        <StyleName>labels</StyleName>
        <Datasource>
            <Parameter name="type">sqlite</Parameter>
            <Parameter name="file">qgis_spatiallite.sqlite</Parameter>
             <Parameter name="base">RESOURCE_PATH</Parameter>
            <Parameter name="geometry_field">geometry</Parameter>
            <Parameter name="table">point</Parameter>
        </Datasource>
</Layer>
```

Any help on this issue will be much appreciated.

**Comment by springmeyer** [comment]
this issue is closed. please create a new one
