### ISSUE TITLE
C++ Text Symbolizer - getting the field name

### ISSUE THREAD

**Issue by millapet** [mapnik/mapnik-support#121]
Hello,
I am using Mapnik 3 and attempting to get back the values I set using the Text Symbolizer and I am having trouble with getting the field name.

I set it like this (same as in the demo):
`  placement_finder->defaults.set_format_tree(std::make_shared<mapnik::formatting::text_node>(parse_expression("[FIELD_NAME]")));` 

And now I would like to get _[FIELD_NAME]_ back, ideally as a string. Is there such a way? 

With the other properties it's pretty straightforward, but I would appreciate a nudge in the right direction for this. 
Petra

**Comment by talaj** [comment]
The `placement_finder->defaults` has [format_tree()](https://github.com/mapnik/mapnik/blob/23492d6742d184219bc1e3f70df1afcd8a19edbd/include/mapnik/text/text_properties.hpp#L196) member which should return the `text_node` with [`get_text()`](https://github.com/mapnik/mapnik/blob/23492d6742d184219bc1e3f70df1afcd8a19edbd/include/mapnik/text/formatting/text.hpp#L36) method, which returns the expression instance of `[FIELD_NAME]`. There is [`to_expression_string()`](https://github.com/mapnik/mapnik/blob/23492d6742d184219bc1e3f70df1afcd8a19edbd/include/mapnik/expression_string.hpp#L40) function to convert the expression instance back to string.

The [format_tree()](https://github.com/mapnik/mapnik/blob/23492d6742d184219bc1e3f70df1afcd8a19edbd/include/mapnik/text/text_properties.hpp#L196) returns a [smart pointer to base class](https://github.com/mapnik/mapnik/blob/23492d6742d184219bc1e3f70df1afcd8a19edbd/include/mapnik/text/formatting/base.hpp#L47), so the pointer has to be dynamic-casted to `text_node` to be able to call `get_text()` on it.

**Comment by millapet** [comment]
Excellent! Thank you very much!
