### ISSUE TITLE
How to prevent rendering label on lower layer if there will be label on higher one?

### ISSUE THREAD

**Issue by zdila** [mapnik/mapnik-support#122]
I would like to prevent rendering label on lower (L) layer if there will be label on higher one (H). I can't change order of the layers because there is another layer which should be above (L) and below (H).

**Comment by talaj** [comment]
With current Mapnik you can only render labels from (H) before (L) with `opacity="0"`, then clear collision detector cache before (H) by `clear-label-cache="true"` to allow to render them again with original opacity. But to clean all the collision cache is probably not desired.
It would need something like [Keyed collision caches](https://github.com/mapycz/mapnik/blob/master/docs/features/keyed-collision-caches.md).

**Comment by zdila** [comment]
Thanks for the answer.
