### ISSUE TITLE
Mapnik tries to load sqlite datasource using shape plugin instead of sqlite plugin

### ISSUE THREAD

**Issue by wibrahim** [mapnik/mapnik-support#13]
Built mapnik for iOS 6.1 from mapnik-ios-framework
On MacOSx 10.8.3 with XCode 4.6.2

Mapnik and dependencies were built using clang++/libstdc++ compiler:

After playing with mapnik loading various shapefiles I tried to change my datasource to use sqlite, cause I wanted to add some geometry constraints to the label placements, which I do not think is doable using shapefiles. 
So I rebuilt mapnik with sqlite support for plugins, I enabled the PLUGIN_LINIKING='static' and got the sqlite.input inside the lib/mapnik/input directory, now when I try to load an sqlite database I get this error:

```
error: Shape Plugin: shapefile 'Library/Application Support/iPhone Simulator/6.1/Applications/E628F20A-FFAD-4712-A1B2-65E89E33F7A1/MB Example.app/qgis_spatiallite.sqlite.shp' does not exist  encountered during parsing of layer 'point' in Layer at line 50
```

My xml datasource part is:

``` xml
<Layer name="point" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        <StyleName>labels</StyleName>
        <Datasource>
            <Parameter name="type">sqlite</Parameter>
            <Parameter name="file">qgis_spatiallite.sqlite</Parameter>
             <Parameter name="base">RESOURCE_PATH</Parameter>
            <Parameter name="geometry_field">geometry</Parameter>
            <Parameter name="table">point</Parameter>
        </Datasource>
</Layer>
```

Any help on this issue will be much appreciated.

**Comment by springmeyer** [comment]
This must be a bug with the fork of mapnik you are using. So, I would bring it up with @PaulWagener as it is likely a problem in his changes to get the sqlite plugin statically linked. Personally I've only tried/tested shape and csv on iOS, so I can only say that those work. Also, we are working on an official way to build plugins statically, but until it is fully working I cannot recommend using sqlite or any other plugins on iOS (only `mapni::memory_datasource` is guaranteed to work). Follow https://github.com/mapnik/mapnik/issues/1821 for more details

**Comment by PaulWagener** [comment]
I'll just drop in to bring some closure on the issue.
The standard way mapnik handles plugins is by dynamically loading .input files with ltdl. Dynamically loading code is strictly forbidden on the iPhone so I hacked around it by statically linking the sqlite and shape plugin. Which can be observed here:
https://github.com/PaulWagener/mapnik/compare/master...ios-static-library#L9R124

I'm not sure why your configuration still tries to load with the shape plugin. As even with the hack it should still load the sqlite plugin. Maybe you somehow got the official mapnik and my fork of it confused?

In any case, any and all .input files will be ignored by the static fork of mapnik.

**Comment by springmeyer** [comment]
Thanks @PaulWagener - yes, I recently removed the ltdl dependency in mapnik master partly for this reason. Now dlopen is called only if dynamically loading, which should/cannot be done on iOS.

**Comment by PaulWagener** [comment]
I was not aware of that, a very welcome addition!
I will update my own iOS Makefile soon to make use of it. And hopefully obsolete my own mapnik fork in the process.

Op 10 mei 2013 om 00:00 heeft Dane Springmeyer notifications@github.com het volgende geschreven:

**Comment by wibrahim** [comment]
@PaulWagener Thanks for the clarification Paul, I checked the diff you linked in your post https://github.com/PaulWagener/mapnik/compare/master...ios-static-library#L9R124 and I checked out a fresh copy of your mapnik-ios-framework from: https://github.com/PaulWagener/mapnik-ios-framework however a comparison for the mapnik/src/datasource_cache.cpp file checked out shows that it does not include any of the changes for the sqlite as for your diff. so I am wondering if I should checkout a different branch for the ios or mapnik to get the sqlite plugin working ?

**Comment by PaulWagener** [comment]
You are absolutely right. The framework project still references commit PaulWagener/mapnik@6b3689301f as a git submodule. While I made two extra commit after that, including sqlite support: https://github.com/PaulWagener/mapnik/commits/ios-static-library

That explains why sqlite was not working in your project. Fixable by explicitly checking out PaulWagener/mapnik@19bebeb before compiling.

**Comment by wibrahim** [comment]
@PaulWagener Thanks for your clarifications, I checked out the static branch and compiled accordingly, everything works fine on the iOS Simulator, but when I try to run on an iPAD I get this error:

```
error: Sqlite Plugin: unable to open database file  encountered during parsing of layer 'point' in Layer at line 26
```

I made sure that I have my database file copied to the iPAD and that libsqlite.a is included as well. 

Also when running inside the simulator I do not get this error but I am facing another weird error. I converted my data from a shapefile to an sqlite database as outlined here: https://github.com/mapnik/mapnik/wiki/SQLite
When I run a style:

``` xml
 <Style name="point">
        <Rule>
            <ShieldSymbolizer base="point-icon" file="point.png" face-name="DejaVu Sans Book" size="8" fill="red" placement="point" dx="0" dy="-10" orientation="0">[NAME]</ShieldSymbolizer>  
        </Rule>
</Style>
<Layer name="point" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        <StyleName>point</StyleName>
        <Datasource>
            <Parameter name="type">sqlite</Parameter>
            <Parameter name="file">countries.sqlite</Parameter>
            <Parameter name="base">RESOURCE_PATH</Parameter>
            <Parameter name="geometry_field">geometry</Parameter>
            <Parameter name="table">countries</Parameter>
        </Datasource>
 </Layer>
```

I get an error:

```
error: Key does not exist: 'name'
```

wondering if my database creation was correct or am I missing something ?

UPDATE:
The casing inside the ShieldSymbolizer is case sensitive with sqlite, I tried [name] instead of [NAME] and that worked fine. I am still not able to run  the same code on the iPAD tho.

Thanks in advance for your help.

**Comment by PaulWagener** [comment]
The "file" parameter should be an absolute path, otherwise mapnik will not be able to find it correctly.
You can use the same trick I used for the 'base' parameter and RESOURCE_PATH in order to fill in the absolute path at runtime.

Word of warning: I never actually got the sqlite plugin working. I gave up when I had to force the postgresql queries into sqlite and failed miserably. Be aware of dragons down that path.

**Comment by wibrahim** [comment]
@PaulWagener Thanks for the warning, Ill stay cautious :) 
I did use your trick with the RESOURCE_PATH and the file parameter and the base parameter are set accordingly, the error I am getting is not that SQLite plugin can not find the file, it actually says that it is "unable to open database file" while in the iOS simulator all works fine ! I checked the built static libraries and they all have the same bindings for all the architectures, so I am not sure why it can not open the file on the iPad specifically.

**Comment by PaulWagener** [comment]
Casually googling your error I get some information that the sqlite gives that error if the database file cannot be accessed in a read-write mode. This is the case if you package your database file as a resource in your XCode project. The iOS security model explicitly forbids writing to such resources. You could try copying the database to the documents directory and then opening the file from there, that way sqlite also has permissions to write to the file.
No guarantees, but worth a shot.

**Comment by wibrahim** [comment]
Thanks @PaulWagener I came to the same conclusion searching over google as well, and I ended up copying the database file from within the resources folder to the Documents folder and that solved the "unable to open database file" error but now I'm facing another error related to memory management that only happen on the iPad not the simulator, and only when I hook up mapnik with sqlite datasource for a layer. Here is the error which I am still investigating:

```
error for object 0x1f85c394: pointer being freed was not allocated
```

It's obviously states that a null object is getting destructed which I traced it back to a std::string object. I googled the error and it more relates to the old iOS where memory management was done manually. What dazzles me is that I did not do any code changes other than changing my xml style to load the layer from an sqlite datasource instead of a shape file, and this error only happens on the iPad not the simulator as I mentioned,  I am trying to re-write my code to be more diligent with memory usage but I appreciate your help if you faced this error before using sqlite plugin. I think the dragons might have started appearing but I wont give up the fight, just not yet :)

**Comment by artemp** [comment]
@wibrahim  - check you're using the same runtime libraries for all c++ modules.

**Comment by wibrahim** [comment]
Ok I solved it. The issue was that if an UIImage is constructed from a mapnik::image_32 that has empty data, iPad crashes trying to free up the underlying buffer of the UIImage and for some reason it does not crash on the simulator. So my fix was to simply not to construct a UIImage if the mapnik renderer returned an empty image_32 buffer.

**Comment by springmeyer** [comment]
what do you mean by `empty` data? A `mapnik::image_32` should always be initialized to a blank/transparent buffer.

**Comment by wibrahim** [comment]
well when watching the `mapnik::image_32::image_data_32` the pData buffer contains unsigned int value of 0 `nil`, so that's what I meant by empty data. Again this crash is not consistent cause when I removed my check it just worked !

**Comment by springmeyer** [comment]
Sounds like you are 1) creating a UIImage from the `mapnik::image_32`, 2) the UIImage is not copying the underlying image buffer but taking a reference to its pointer, and 3) the `mapnik::image_32` is going out of scope or getting deleted before the UIImage is done with the underlying buffer.

Here is a simple and reliable way of moving the data from a `mapnik::image_32` to a `UIImage`:

``` c++
std::string png_data = mapnik::save_to_string(im,"png:z=1");
return [UIImage imageWithData:[NSData dataWithBytes:png_data.c_str() length:png_data.size()]];
```

Ideally the `png` encoding step here could be avoided, but this works nonetheless.

**Comment by wibrahim** [comment]
Thanks @springmeyer  I was already using the `mapnik::save_to_string` for converting between `mapnik::image_32` and `UIImage`. I googled around and found a similar issue that happens when using `mapnik::cairo_rendere` and iin a multi-threaded environment, and it had something to do with the thread-support inside cairo and pixman libraries. 
I am actually not using cairo but using `mapnik::agg_renderer` in a multi-threaded environment to produce tiles, so guessing if this issue might be related to threading support inside the agg_renderer as well ? Again this crash is very sporadic, it does not happen consistently.

**Comment by springmeyer** [comment]
Right cairo has some threading bugs. But no, our agg_renderer is thread safe so I really doubt that is the problem you are seeing. Can you post your code?

**Comment by wibrahim** [comment]
Sure, here is my code:

``` objectiveC
-(UIImage *) imageForTile:(RMTile)tile WithBoundingBox: (RMSphericalTrapezium) boundingBox
{
    UIImage* image = nil;
    try
    {

        mapnik::freetype_engine::register_font(self.fontFile.UTF8String);
        mapnik::register_image_reader("png",mapnik::create_png_reader);

        // set up renderable image and map canvas
        NSString *style = [NSString stringWithContentsOfFile:self.styleFile encoding:NSUTF8StringEncoding error:nil];
        style = [style stringByReplacingOccurrencesOfString:@"RESOURCE_PATH" withString:[NSBundle mainBundle].resourcePath];

        mapnik::Map mapnikMap(kDefaultTileSize, kDefaultTileSize);
        mapnik::load_map_string(mapnikMap, std::string(style.UTF8String));

        //convert the Tile bounding box lat/long to the map projection
        mapnik::projection destProj( mapnikMap.srs() );
        double c0x = boundingBox.northEast.longitude;
        double c0y = boundingBox.northEast.latitude;
        double c1x = boundingBox.southWest.longitude;
        double c1y = boundingBox.southWest.latitude;
        destProj.forward(c0x, c0y);
        destProj.forward(c1x, c1y);

        mapnik::box2d<double> bbox(c0x, c0y, c1x, c1y);
        mapnikMap.zoom_to_box(bbox);
        if( mapnikMap.buffer_size() < 128)
        {
            mapnikMap.set_buffer_size(128);
        }

        // Render image with Agg renderer
        mapnik::image_32 im(kDefaultTileSize, kDefaultTileSize);
        mapnik::agg_renderer<mapnik::image_32> ren(mapnikMap,im);
        ren.apply();

        //save the image to a string
        std::string strImageData = mapnik::save_to_string(im, "png256");

        if( !strImageData.empty() ) //safe guard for weird crashing issue.
        {
            image = [[UIImage alloc] initWithData: [[NSData alloc ] initWithBytes: strImageData.data() length:  strImageData.length() ]];
            NSLog(@"resultImg width:%f, height:%f",image.size.width,image.size.height);
        }
    }
    catch (std::exception const& ex)
    {
        NSLog(@"error: %s",ex.what());
    }
    return image;
}
```

**Comment by rghosh0** [comment]
I notice that this issue is closed, but I don't see a solution to the empty image_32 buffer problem, nor do I see a new issue created for this problem.  Was the problem not related to mapnik after all?

**Comment by wibrahim** [comment]
I was not sure what the problem of the empty buffer was related to mapnik or iOS forcing garbage collection on the sting itself. As I mentioned my code sample included above worked fine at the time.
