### ISSUE TITLE
Is there a way to specify initial spacing for MarkersSymbolizer?

### ISSUE THREAD

**Issue by zdila** [mapnik/mapnik-support#137]
We would like to put two MarkerSymbolizers on a line, one shifted so that they would not cover. Is something like that possible?

```
MarkerSymbolizer      1: -x---x---x---x---x-...
MarkerSymbolizer      2: ---o---o---o---o---...
MarkerSymbolizer result: -x-o-x-o-x-o-x-o-x-...
```

**Comment by talaj** [comment]
Not easily, what I know. Offset is always [spacing / 2](https://github.com/mapnik/mapnik/blob/c7d29b826fb6ceb2034220cd970c871bb5929dd3/include/mapnik/markers_placements/line.hpp#L80). There is no `dy` like in Text/Shield symbolizer.
