### ISSUE TITLE
geometry name lookup failed if UV_THREADPOOL_SIZE > 10

### ISSUE THREAD

**Issue by zdila** [mapnik/mapnik-support#143]
Hello,

We are doing parallel mapnik rendering but when we set `UV_THREADPOOL_SIZE` higher than 10 then rendering immediately fails with following error:

```
Error: PostGIS: geometry name lookup failed for table '(select type, geometry, z_order from osm_landusages where geometry && !bbox!
        union all select 'feat:' || type, geometry, 1000 as z_order from osm_feature_polys where geometry && !bbox!
        order by z_order) as foo'. Please manually provide the 'geometry_field' parameter or add an entry in the geometry_columns for '(select type, geometry, z_order from osm_landusages where geometry && !bbox!
        union all select 'feat:' || type, geometry, 1000 as z_order from osm_feature_polys where geometry && !bbox!
        order by z_order) as foo'.
```

Please see also #114

**Comment by talaj** [comment]
Hi!

I think this can be due to exceeding connection pool size which is by default 10:
https://github.com/mapnik/mapnik/blob/6e40d4bcf7d6dfc5b33cd0a47dadd6f057b3e402/plugins/input/postgis/postgis_datasource.cpp#L75

Try to set `max_size` parameter of the datasource to some higher value.

**Comment by zdila** [comment]
That did the trick! Thank you!
