### ISSUE TITLE
problem building mapnik under debian testing

### ISSUE THREAD

**Issue by zdila** [mapnik/mapnik-support#18]
hello

I am running debian testing and after latest updates (both mapnik and debian).

scons: done reading SConscript files.
scons: Building targets ...
g++ -o demo/c++/rundemo demo/c++/rundemo.o -Ldeps/agg -Lsrc -L/usr/lib -L/usr/lib/x86_64-linux-gnu -lmapnik -lagg -lfreetype -licuuc -lboost_filesystem -lboost_system -lboost_regex -lproj -lpng -ltiff -lwebp -ljpeg -lxml2 -lz -lboost_thread -licui18n -ldl -lcairo
/usr/bin/ld: warning: libicuuc.so.48, needed by /usr/lib/libboost_regex.so, may conflict with libicuuc.so.52
/usr/bin/ld: warning: libicui18n.so.48, needed by /usr/lib/libboost_regex.so, may conflict with libicui18n.so.52
src/libmapnik.so: undefined reference to `boost::re_detail::icu_regex_traits_implementation::do_transform(int const_, int const_, icu_52::Collator const*) const'
collect2: error: ld returned 1 exit status

from https://github.com/mapnik/mapnik/wiki/InstallationTroubleshooting#boost-undefined-symbols i read that i should build libboost from sources. is it really necessary? i am asking because couple weeks ago it worked from libboost from debian repositories. also i have other software installed from debian repositories that depend on libboost from debian repositories (currently ver 1.54).

Is there any other "workaround"?

Thanks in advance!

**Comment by springmeyer** [comment]
Another workaround is to avoid Mapnik building and linking against icu 52. In short the problem is that you somehow have two icu versions on your system and Mapnik is building against the newer one (which would be ideal if not for boost being built against the older one). So take a look at what icu library is pointed at by /usr/lib/libicuuc.so. Use 'ls -l /usr/lib/libicuuc*' to see what symlinks point where.

**Comment by zdila** [comment]
Thanks for answer.

I have none in /usr/lib/ but there are some in /usr/lib/x86_64-linux-gnu/:

-rw-r--r-- 1 root root 2660178 Dec  3 22:15 /usr/lib/x86_64-linux-gnu/libicuuc.a
lrwxrwxrwx 1 root root      16 Dec  3 22:15 /usr/lib/x86_64-linux-gnu/libicuuc.so -> libicuuc.so.52.1
lrwxrwxrwx 1 root root      18 Nov 13 22:32 /usr/lib/x86_64-linux-gnu/libicuuc.so.48 -> libicuuc.so.48.1.1
-rw-r--r-- 1 root root 1472648 Nov 13 22:32 /usr/lib/x86_64-linux-gnu/libicuuc.so.48.1.1
lrwxrwxrwx 1 root root      16 Dec  3 22:15 /usr/lib/x86_64-linux-gnu/libicuuc.so.52 -> libicuuc.so.52.1
-rw-r--r-- 1 root root 1525776 Dec  3 22:15 /usr/lib/x86_64-linux-gnu/libicuuc.so.52.1

I've tried to modify link libicuuc.so to point it to libicuuc.so.48.1.1, and also for libicui18n.so, but now I have different compilation errors:

g++ -o demo/c++/rundemo demo/c++/rundemo.o -Ldeps/agg -Lsrc -L/usr/lib -L/usr/lib/x86_64-linux-gnu -lmapnik -lagg -lfreetype -licuuc -lboost_filesystem -lboost_system -lboost_regex -lproj -lpng -ltiff -lwebp -ljpeg -lxml2 -lz -lboost_thread -licui18n -ldl -lcairo
src/libmapnik.so: undefined reference to `icu_52::UnicodeString::doReverse(int, int)'
src/libmapnik.so: undefined reference to`icu_52::UnicodeString::doReplace(int, int, unsigned short const*, int, int)'
src/libmapnik.so: undefined reference to `u_strToUTF8_52'
src/libmapnik.so: undefined reference to`u_tolower_52'
src/libmapnik.so: undefined reference to `ubidi_getBaseDirection_52'
... and many more

I can't remove package libicu52 because libreoffice-\* and other useful software packages depends on it. Is there any way to tell the builder to use ICU 48?

**Comment by springmeyer** [comment]
Yes, you need to ensure the headers for icu 48 are what are installed. Looks like you have the 52 headers. Also be sure to run 'make clean' in Mapnik directory after changing things.

**Comment by zdila** [comment]
Unfortunately there is no libicu48-dev package in Debian but only libicu-dev which contains headers of ICU 52.

It seems that Debian testing now doesn't allow buildnig sources against ICU 48 but only use binaries against ICU 48 (and 52) :-(

Don't you plant to start using ICU 52 in Mapnik? ;-)

**Comment by springmeyer** [comment]
Mapnik works fine with any recent icu version. This looks like a Debian packaging bug. You can't compile against the headers of one version of icu and link against another. This is not a Mapnik issue therefore.

**Comment by springmeyer** [comment]
Sorry forgot this was a support ticket not a bug ticket. Reopening until resolved. Seems like you need to either update the boost package to use icu52 or build boost from source against icu 52.

**Comment by zdila** [comment]
After latest system update all compiles successfully. Thanks for the support.
