### ISSUE TITLE
Ubuntu 14.04 - scons errors

### ISSUE THREAD

**Issue by augaug** [mapnik/mapnik-support#20]
I get the following errors when compiling on 14.04:

_scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/image_filter_types.os -c -Wall -Wsign-compare -pthread -ftemplate-depth-300 -O3 -fno-strict-aliasing -finline-functions -Wno-inline -Wno-parentheses -Wno-char-subscripts -fPIC -DSHAPE_MEMORY_MAPPED_FILE -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -Ideps -Ideps/clipper/include -Ideps/agg/include -I. -Iinclude -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/gdal -I/usr/include/postgresql -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 src/image_filter_types.cpp
In file included from include/mapnik/image_filter_grammar.hpp:31:0,
                 from src/image_filter_types.cpp:24:
include/mapnik/image_filter.hpp:420:8: error: ‘uint8_t’ does not name a type
 inline uint8_t apply_alpha_shift(double source, double match, double alpha)
        ^
include/mapnik/image_filter.hpp: In function ‘void mapnik::filter::apply_filter(Src&, const mapnik::filter::color_to_alpha&)’:
include/mapnik/image_filter.hpp:439:13: error: ‘uint8_t’ was not declared in this scope
             uint8_t & r = get_color(src_it[x], red_t());
             ^
include/mapnik/image_filter.hpp:439:13: note: suggested alternative:
In file included from include/mapnik/global.hpp:27:0,
                 from include/mapnik/color.hpp:28,
                 from include/mapnik/image_filter_types.hpp:28,
                 from src/image_filter_types.cpp:23:
/usr/local/include/boost/cstdint.hpp:211:30: note:   ‘boost::uint8_t’
      typedef unsigned char   uint8_t;
                              ^
In file included from include/mapnik/image_filter_grammar.hpp:31:0,
                 from src/image_filter_types.cpp:24:
include/mapnik/image_filter.hpp:439:23: error: ‘r’ was not declared in this scope
             uint8_t & r = get_color(src_it[x], red_t());
                       ^
include/mapnik/image_filter.hpp:440:23: error: ‘g’ was not declared in this scope
             uint8_t & g = get_color(src_it[x], green_t());
                       ^
include/mapnik/image_filter.hpp:441:23: error: ‘b’ was not declared in this scope
             uint8_t & b = get_color(src_it[x], blue_t());
                       ^
include/mapnik/image_filter.hpp:442:23: error: ‘a’ was not declared in this scope
             uint8_t & a = get_color(src_it[x], alpha_t());
                       ^
include/mapnik/image_filter.hpp:465:47: error: there are no arguments to ‘apply_alpha_shift’ that depend on a template parameter, so a declaration of ‘apply_alpha_shift’ must be available [-fpermissive]
                 r = apply_alpha_shift(sr,cr,xa);
                                               ^
include/mapnik/image_filter.hpp:465:47: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
include/mapnik/image_filter.hpp:466:47: error: there are no arguments to ‘apply_alpha_shift’ that depend on a template parameter, so a declaration of ‘apply_alpha_shift’ must be available [-fpermissive]
                 g = apply_alpha_shift(sg,cg,xa);
                                               ^
include/mapnik/image_filter.hpp:467:47: error: there are no arguments to ‘apply_alpha_shift’ that depend on a template parameter, so a declaration of ‘apply_alpha_shift’ must be available [-fpermissive]
                 b = apply_alpha_shift(sb,cb,xa);
                                               ^
include/mapnik/image_filter.hpp:470:33: error: expected type-specifier before ‘uint8_t’
                 a = static_cast<uint8_t>(std::floor((xa_255.0)+.5));
                                 ^
include/mapnik/image_filter.hpp:470:33: error: expected ‘>’ before ‘uint8_t’
include/mapnik/image_filter.hpp:470:33: error: expected ‘(’ before ‘uint8_t’
include/mapnik/image_filter.hpp:470:68: error: expected ‘)’ before ‘;’ token
                 a = static_cast<uint8_t>(std::floor((xa_255.0)+.5));
                                                                    ^
include/mapnik/image_filter.hpp: In function ‘void mapnik::filter::apply_filter(Src&, const mapnik::filter::colorize_alpha&)’:
include/mapnik/image_filter.hpp:500:17: error: ‘uint8_t’ was not declared in this scope
                 uint8_t & r = get_color(src_it[x], red_t());
                 ^
include/mapnik/image_filter.hpp:500:17: note: suggested alternative:
In file included from include/mapnik/global.hpp:27:0,
                 from include/mapnik/color.hpp:28,
                 from include/mapnik/image_filter_types.hpp:28,
                 from src/image_filter_types.cpp:23:
/usr/local/include/boost/cstdint.hpp:211:30: note:   ‘boost::uint8_t’
      typedef unsigned char   uint8_t;
                              ^
In file included from include/mapnik/image_filter_grammar.hpp:31:0,
                 from src/image_filter_types.cpp:24:
include/mapnik/image_filter.hpp:500:27: error: ‘r’ was not declared in this scope
                 uint8_t & r = get_color(src_it[x], red_t());
                           ^
include/mapnik/image_filter.hpp:501:27: error: ‘g’ was not declared in this scope
                 uint8_t & g = get_color(src_it[x], green_t());
                           ^
include/mapnik/image_filter.hpp:502:27: error: ‘b’ was not declared in this scope
                 uint8_t & b = get_color(src_it[x], blue_t());
                           ^
include/mapnik/image_filter.hpp:503:27: error: ‘a’ was not declared in this scope
                 uint8_t & a = get_color(src_it[x], alpha_t());
                           ^
include/mapnik/image_filter.hpp:541:21: error: ‘uint8_t’ was not declared in this scope
                     uint8_t & r = get_color(src_it[x], red_t());
                     ^
include/mapnik/image_filter.hpp:541:21: note: suggested alternative:
In file included from include/mapnik/global.hpp:27:0,
                 from include/mapnik/color.hpp:28,
                 from include/mapnik/image_filter_types.hpp:28,
                 from src/image_filter_types.cpp:23:
/usr/local/include/boost/cstdint.hpp:211:30: note:   ‘boost::uint8_t’
      typedef unsigned char   uint8_t;
                              ^
In file included from include/mapnik/image_filter_grammar.hpp:31:0,
                 from src/image_filter_types.cpp:24:
include/mapnik/image_filter.hpp:541:31: error: ‘r’ was not declared in this scope
                     uint8_t & r = get_color(src_it[x], red_t());
                               ^
include/mapnik/image_filter.hpp:542:31: error: ‘g’ was not declared in this scope
                     uint8_t & g = get_color(src_it[x], green_t());
                               ^
include/mapnik/image_filter.hpp:543:31: error: ‘b’ was not declared in this scope
                     uint8_t & b = get_color(src_it[x], blue_t());
                               ^
include/mapnik/image_filter.hpp:544:31: error: ‘a’ was not declared in this scope
                     uint8_t & a = get_color(src_it[x], alpha_t());
                               ^
include/mapnik/image_filter.hpp: In function ‘void mapnik::filter::apply_filter(Src&, const mapnik::filter::scale_hsla&)’:
include/mapnik/image_filter.hpp:606:17: error: ‘uint8_t’ was not declared in this scope
                 uint8_t & r = get_color(src_it[x], red_t());
                 ^
include/mapnik/image_filter.hpp:606:17: note: suggested alternative:
In file included from include/mapnik/global.hpp:27:0,
                 from include/mapnik/color.hpp:28,
                 from include/mapnik/image_filter_types.hpp:28,
                 from src/image_filter_types.cpp:23:
/usr/local/include/boost/cstdint.hpp:211:30: note:   ‘boost::uint8_t’
      typedef unsigned char   uint8_t;
                              ^
In file included from include/mapnik/image_filter_grammar.hpp:31:0,
                 from src/image_filter_types.cpp:24:
include/mapnik/image_filter.hpp:606:27: error: ‘r’ was not declared in this scope
                 uint8_t & r = get_color(src_it[x], red_t());
                           ^
include/mapnik/image_filter.hpp:607:27: error: ‘g’ was not declared in this scope
                 uint8_t & g = get_color(src_it[x], green_t());
                           ^
include/mapnik/image_filter.hpp:608:27: error: ‘b’ was not declared in this scope
                 uint8_t & b = get_color(src_it[x], blue_t());
                           ^
include/mapnik/image_filter.hpp:609:27: error: ‘a’ was not declared in this scope
                 uint8_t & a = get_color(src_it[x], alpha_t());
                           ^
include/mapnik/image_filter.hpp:641:41: error: expected type-specifier before ‘uint8_t’
                         a = static_cast<uint8_t>(std::floor((a2 \* 255.0) +.5));
                                         ^
include/mapnik/image_filter.hpp:641:41: error: expected ‘>’ before ‘uint8_t’
include/mapnik/image_filter.hpp:641:41: error: expected ‘(’ before ‘uint8_t’
include/mapnik/image_filter.hpp:641:79: error: expected ‘)’ before ‘;’ token
                         a = static_cast<uint8_t>(std::floor((a2 \* 255.0) +.5));
                                                                               ^
include/mapnik/image_filter.hpp:665:33: error: expected type-specifier before ‘uint8_t’
                 r = static_cast<uint8_t>(std::floor((r2_255.0)+.5));
                                 ^
include/mapnik/image_filter.hpp:665:33: error: expected ‘>’ before ‘uint8_t’
include/mapnik/image_filter.hpp:665:33: error: expected ‘(’ before ‘uint8_t’
include/mapnik/image_filter.hpp:665:68: error: expected ‘)’ before ‘;’ token
                 r = static_cast<uint8_t>(std::floor((r2_255.0)+.5));
                                                                    ^
include/mapnik/image_filter.hpp:666:33: error: expected type-specifier before ‘uint8_t’
                 g = static_cast<uint8_t>(std::floor((g2_255.0)+.5));
                                 ^
include/mapnik/image_filter.hpp:666:33: error: expected ‘>’ before ‘uint8_t’
include/mapnik/image_filter.hpp:666:33: error: expected ‘(’ before ‘uint8_t’
include/mapnik/image_filter.hpp:666:68: error: expected ‘)’ before ‘;’ token
                 g = static_cast<uint8_t>(std::floor((g2_255.0)+.5));
                                                                    ^
include/mapnik/image_filter.hpp:667:33: error: expected type-specifier before ‘uint8_t’
                 b = static_cast<uint8_t>(std::floor((b2_255.0)+.5));
                                 ^
include/mapnik/image_filter.hpp:667:33: error: expected ‘>’ before ‘uint8_t’
include/mapnik/image_filter.hpp:667:33: error: expected ‘(’ before ‘uint8_t’
include/mapnik/image_filter.hpp:667:68: error: expected ‘)’ before ‘;’ token
                 b = static_cast<uint8_t>(std::floor((b2_255.0)+.5));
                                                                    ^
include/mapnik/image_filter.hpp: In function ‘void mapnik::filter::apply_filter(Src&, const mapnik::filter::gray&)’:
include/mapnik/image_filter.hpp:690:13: error: ‘uint8_t’ was not declared in this scope
             uint8_t & r = get_color(src_it[x], red_t());
             ^
include/mapnik/image_filter.hpp:690:13: note: suggested alternative:
In file included from include/mapnik/global.hpp:27:0,
                 from include/mapnik/color.hpp:28,
                 from include/mapnik/image_filter_types.hpp:28,
                 from src/image_filter_types.cpp:23:
/usr/local/include/boost/cstdint.hpp:211:30: note:   ‘boost::uint8_t’
      typedef unsigned char   uint8_t;
                              ^
In file included from include/mapnik/image_filter_grammar.hpp:31:0,
                 from src/image_filter_types.cpp:24:
include/mapnik/image_filter.hpp:690:23: error: ‘r’ was not declared in this scope
             uint8_t & r = get_color(src_it[x], red_t());
                       ^
include/mapnik/image_filter.hpp:691:23: error: ‘g’ was not declared in this scope
             uint8_t & g = get_color(src_it[x], green_t());
                       ^
include/mapnik/image_filter.hpp:692:23: error: ‘b’ was not declared in this scope
             uint8_t & b = get_color(src_it[x], blue_t());
                       ^
include/mapnik/image_filter.hpp:693:23: error: expected ‘;’ before ‘v’
             uint8_t   v = uint8_t((4915 \* r + 9667 \* g + 1802 \* b + 8192) >> 14);
                       ^
include/mapnik/image_filter.hpp:694:25: error: ‘v’ was not declared in this scope
             r = g = b = v;
                         ^
include/mapnik/image_filter.hpp: In function ‘void mapnik::filter::apply_filter(Src&, const mapnik::filter::invert&)’:
include/mapnik/image_filter.hpp:756:13: error: ‘uint8_t’ was not declared in this scope
             uint8_t   a = get_color(src_it[x], alpha_t());
             ^
include/mapnik/image_filter.hpp:756:13: note: suggested alternative:
In file included from include/mapnik/global.hpp:27:0,
                 from include/mapnik/color.hpp:28,
                 from include/mapnik/image_filter_types.hpp:28,
                 from src/image_filter_types.cpp:23:
/usr/local/include/boost/cstdint.hpp:211:30: note:   ‘boost::uint8_t’
      typedef unsigned char   uint8_t;
                              ^
In file included from include/mapnik/image_filter_grammar.hpp:31:0,
                 from src/image_filter_types.cpp:24:
include/mapnik/image_filter.hpp:756:23: error: expected ‘;’ before ‘a’
             uint8_t   a = get_color(src_it[x], alpha_t());
                       ^
include/mapnik/image_filter.hpp:757:23: error: ‘r’ was not declared in this scope
             uint8_t & r = get_color(src_it[x], red_t());
                       ^
include/mapnik/image_filter.hpp:758:23: error: ‘g’ was not declared in this scope
             uint8_t & g = get_color(src_it[x], green_t());
                       ^
include/mapnik/image_filter.hpp:759:23: error: ‘b’ was not declared in this scope
             uint8_t & b = get_color(src_it[x], blue_t());
                       ^
include/mapnik/image_filter.hpp:760:17: error: ‘a’ was not declared in this scope
             r = a - r;
                 ^
scons: **\* [src/image_filter_types.os] Error 1
scons: building terminated because of errors.
make: **\* [mapnik] Error 2_

Any ideas? Thanks!

**Comment by springmeyer** [comment]
thanks for the report - what boost version and what mapnik version are you trying to build?

**Comment by augaug** [comment]
Looks like 1.54 and 2.3

**Comment by springmeyer** [comment]
how exactly did you download Mapnik 2.3? From the github 2.3.x branch? Or how? I need to know exactly to be able to replicate.

**Comment by augaug** [comment]
from ppa:mapnik/nightly-2.3

**Comment by springmeyer** [comment]
`ppa:mapnik/nightly-2.3` is a mapnik package and not the mapnik sources. It looks like you are compiling from source. What exact source code did you download?

**Comment by augaug** [comment]
git clone https://github.com/mapnik/mapnik mapnik-2.3.x -b 2.3.x - ah sorry about that, I'm just going through the steps on the github Ubuntu page

**Comment by augaug** [comment]
Not sure if it matters but I'm on Xubuntu distro vs. Ubuntu

**Comment by springmeyer** [comment]
@augaug - looking at this again I'm presuming it is some kind of C++ library or compiler issue on your distribution that is likely fixable by updated your system or installing the g++ development headers. I've not seen any other reports like this for Mapnik. Please re-open if you are still seeing the problem.

**Comment by flyingsnowers** [comment]
I got a same problem，do you solve this problem？and can you tell me  how to solve this  problem？
