### ISSUE TITLE
PolygonPatternSymbolizer works using XML, but not Python

### ISSUE THREAD

**Issue by ekelleyv** [mapnik/mapnik-support#22]
I can get the polygon pattern symbolizer to work using an xml file and using python's `mapnik.load_map()`. However, if I try and create a `PolygonPatternSymbolizer()`, it does not render. No errors, no warnings, it just does not show up on the map (when just `PolygonSymbolizer()` works fine). Here is the relevant xml and python:

``` xml
<Rule>
    <PolygonPatternSymbolizer file="/vagrant/buster/tileserver/img/field_pattern.png"/>
</Rule>
```

``` python
rule = Rule()
fill = PolygonPatternSymbolizer()
fill.file = "/vagrant/buster/tileserver/img/field_pattern.png"
rule.symbols.append(fill)
```

This is on the current commit in master, built from source. Anything obvious I am missing?

**Comment by ekelleyv** [comment]
Just found this, which I guess explains everything:
 https://github.com/mapnik/mapnik/issues/2225

**Comment by springmeyer** [comment]
> Just found this, which I guess explains everything:

Correct, python bindings are not fully viable at the moment in master. Are you able instead to use XML for now?

**Comment by ekelleyv** [comment]
Possibly. I may just drop back to the last tagged release until this gets sorted out. Any idea on a timeline?

The odd thing is that most of the python bindings work (LinePatternSymbolizer is fine, for example), it is just the pattern symbolizer that was giving me trouble.

Thanks!

**Comment by springmeyer** [comment]
My hope is python bindings will be working within 2-3 months. Its not a huge lift but I need to find time to test things and make minor fixes.

> The odd thing is that most of the python bindings work (LinePatternSymbolizer is fine, for example), it is just the pattern symbolizer that was giving me trouble.

That is odd. Can you comment with more details at https://github.com/mapnik/mapnik/issues/2324? Note: I've closed mapnik/mapnik#2225 since it is out of date (much of the bindings have been repaired/are working).

**Comment by ekelleyv** [comment]
Would be happy to comment, but there are really no more details than what I have said here. If I just replace Polygon with Line in the code above, a line pattern appears along the perimeter of the polygon.

**Comment by springmeyer** [comment]
Thanks for the comment at https://github.com/mapnik/mapnik/issues/2324#issuecomment-56445474, thats just fine. I'll close this now and we'll track the fixes at that ticket. Thanks.

**Comment by ekelleyv** [comment]
No problem! I moved to using XML in the meantime. Thanks for the help.
