### ISSUE TITLE
Problems installing mapnik on OSX 10.6 (and everywhere else)

### ISSUE THREAD

**Issue by arenol** [mapnik/mapnik-support#25]
I badly need mapnik to automatically render files. But I can't install it and make it work on any computer that I have, which is.
1) A PowerMac running OSX 10.6.8
2) An iMac runnin OSX 
3) A Windows PC rinning Windows 7
4) A Linux pc running Debin

Obviousliy  the culprit is related to Python, which comes presinstalled on some computers, and which some other software installs their own versions of.  An then I allways end up with a mispatch between the versions, and the solutions doesn't make sense, with either python not finding the library, complaing that the DLL is not a valid Win32 software, or Fatal Python error: Interpreter not initialized (version mismatch?).

And I'm not much of a nerd, so I need everyting with tea spoons.

Let's stick with my personal PowerMac running OSX 10.6.8 (snow leopard).

At one point I found references to the port command, and I also found references to directories /opt/... , neither of which I have.  I ended up installing MacPort and i now both have port and /opt directories (I have no clue what port does and why it creates an /opt tree).

I also suspect that the proeblem is related to boost. So the last thing I deed before installing MacPort was to:

brew uninstall mapnik
brew unistall boost
brew uninstall python.

Then, after installin MacPort installed back;

brew install python
brew install boost
brew install mapnik

Now trying out "import mapnik" in python and get the following error:
    Fatal Python error: Interpreter not initialized (version mismatch?)

Trying to find information about it on the Internet, and finds several pages (none of them helpful).

Note that I have also modified my /etc/paths file so /usr/local/bin is listed before /usr/bin (as the brew python gets installed in /usr/local/bin.  The versions of python and mapnik that I got installed is Python 2.7.8 and mapnik 2.2.0.

Looking under the section Python Version Mismatch at https://github.com/mapnik/mapnik/wiki/InstallationTroubleshooting

I try:

otool -L /opt/local/lib/libboost_python-mt.dylib | grep Python
otool: can't open file: /opt/local/lib/libboost_python-mt.dylib (No such file or directory)

But 

otool -L /usr/local/lib/libboost_python-mt.dylib | grep Python
/System/Library/Frameworks/Python.framework/Versions/2.6/Python (compatibility version 2.6.0, current version 2.6.1)

So there is a version mismatch (but I don't understand why I should look int /opt/local/lib and not /usr/local/lib

The trouble shooting page above suggests:
"Solution: Usually you must rebuild boost_python so that it links against the correct version of Python, or you can use the install_name_tool to on-the-fly change the linking paths. In rarer cases you may need to rebuild Mapnik as well."

Well, how do I rebuild boost_python so it links agains the correct version of python (I hoped that brew uninstall/install boost would solve that proeblem?)

And how do I run the install_name_tool?

Well, on https://trac.macports.org/ticket/21169 I fond the following command

install_name_tool -change /System/Library/Frameworks/Python.framework/Versions/2.6/Python /opt/local/Library/Frameworks/Python.framework/Versions/2.6/Python /opt/local/lib/libboost_python-mt.dylib

I don't have any /opt/local/Library folder and not any
/System/Library/Frameworks/Python.framework/Versions/2.7/ directory, either.

I don't understand anything, and I am completely lost.

Could anyone help me out?

Agnar

**Comment by springmeyer** [comment]
I would recommend not using macports and only using homebrew on OSX. and if your don't install a custom python but rather use the system python then you will not run into the boost python linking mismatch.

That said a ppc OS X 10.6 Mac is very old and not something we officially support anymore. it might work but I would highly recommend using at least 10.8.

**Comment by springmeyer** [comment]
@arenol how have you progressed here?

**Comment by arenol** [comment]
Yep!

I finally managed to install it on the iMac running Maverik.

Simply by downloading the installer and install from that.  Using brew 
did not work (I thought brew should be the fool-proof way, but it wasn't)!

Agnar

Agnar Renolen
eMap as (www.emap.no)
Vegamot 4B, 7048 Trondheim
tlf: 489 50 480 (dir)
