### ISSUE TITLE
SVG and stroke color

### ISSUE THREAD

**Issue by richterb** [mapnik/mapnik-support#27]
I am rendering various SVG icons using a `MarkersSymbolizer`, and I want to add a small outline on my SVG icons, using a simple `stroke="#ffffff"` attribute.

Unfortunately, while it works on many of my SVG files (although I often have to add explicit `stroke` and `fill` in my SVG file), there are some SVG icons that won't display any stroke. I have taken a long look at the differences between the ones that work and the ones that don't, and I can't seem to find the problem (both are a single `<path />`, don't seem to have any exotic thing...).

Do you know of any problem or caveat with SVGs so that I maybe I can find the cause of the absence of stroke? I can provide you with two simple examples (one that works and one that doesn't).

I'm using Mapnik 3.0.0-pre and the AGG renderer.

Thanks!

**Comment by springmeyer** [comment]
Currently stroke and fill properties are only respected if the original SVG has some stroke or fill attribute. This ended up this way due to some limitations in Mapnik that I think are no longer blockers: we may now be able to allow you to selectively add stroke properties even if the path had `stroke="none"` or no stroke properties before. The change to get there would be:

``` diff
diff --git a/src/marker_helpers.cpp b/src/marker_helpers.cpp
index e4aeeb4..8273acf 100644
--- a/src/marker_helpers.cpp
+++ b/src/marker_helpers.cpp
@@ -79,39 +79,38 @@ bool push_explicit_style(svg_attribute_type const& src,
             success = true;
             dst.push_back(src[i]);
             mapnik::svg::path_attributes & attr = dst.last();
-            if (attr.stroke_flag)
+            if (stroke_width)
             {
-                if (stroke_width)
-                {
-                    attr.stroke_width = *stroke_width;
-                }
-                if (stroke_color)
-                {
-                    color const& s_color = *stroke_color;
-                    attr.stroke_color = agg::rgba(s_color.red()/255.0,
-                                                  s_color.green()/255.0,
-                                                  s_color.blue()/255.0,
-                                                  s_color.alpha()/255.0);
-                }
-                if (stroke_opacity)
-                {
-                    attr.stroke_opacity = *stroke_opacity;
-                }
+                attr.stroke_width = *stroke_width;
+                attr.stroke_flag = true;
             }
-            if (attr.fill_flag)
+            if (stroke_color)
             {
-                if (fill_color)
-                {
-                    color const& f_color = *fill_color;
-                    attr.fill_color = agg::rgba(f_color.red()/255.0,
-                                                f_color.green()/255.0,
-                                                f_color.blue()/255.0,
-                                                f_color.alpha()/255.0);
-                }
-                if (fill_opacity)
-                {
-                    attr.fill_opacity = *fill_opacity;
-                }
+                color const& s_color = *stroke_color;
+                attr.stroke_color = agg::rgba(s_color.red()/255.0,
+                                              s_color.green()/255.0,
+                                              s_color.blue()/255.0,
+                                              s_color.alpha()/255.0);
+                attr.stroke_flag = true;
+            }
+            if (stroke_opacity)
+            {
+                attr.stroke_opacity = *stroke_opacity;
+                attr.stroke_flag = true;
+            }
+            if (fill_color)
+            {
+                color const& f_color = *fill_color;
+                attr.fill_color = agg::rgba(f_color.red()/255.0,
+                                            f_color.green()/255.0,
+                                            f_color.blue()/255.0,
+                                            f_color.alpha()/255.0);
+                attr.fill_flag = true;
+            }
+            if (fill_opacity)
+            {
+                attr.fill_opacity = *fill_opacity;
+                attr.fill_flag = true;
             }
         }
         return success;
```

Do you have the ability to test that patch and recompile?

**Comment by springmeyer** [comment]
went ahead and implemented this in https://github.com/mapnik/mapnik/issues/2609

**Comment by richterb** [comment]
I applied your patch and tested it, and indeed, it now draws strokes on SVGs that don't have them already. That's clearly a good improvement. :)

However, it doesn't solve the mystery of why some SVGs don't draw strokes. By looking closely on another screen, it appears it actually has a stroke, but a really really transparent one. In both cases, the SVG is a single Path with no attribute at all. They both come from different sources so they may have wildly different proportions (I harmonized the viewBox in the `svg` tag when searching for the cause).

Here's the "good" one:

``` xml
<svg width="2048" height="2048" viewBox="0 0 2048 2048" xmlns="http://www.w3.org/2000/svg">
<path d="M36.111,0L5.556,27.778h16.667L0,50h16.667L0,72.222h27.778v16.666v2.779v2.777
    c0,3.078,2.478,5.556,5.555,5.556h5.557c3.077,0,5.555-2.478,5.555-5.556v-2.777v-2.779V72.222h27.779L55.557,50h16.667
    L49.999,27.777h16.667L36.111,0z"/>
</svg>
```

![screen shot 2014-12-17 at 0 31 06](https://cloud.githubusercontent.com/assets/1935200/5464180/1f965504-8585-11e4-90bc-4e3139ebaffb.png)

And the weird one:

``` xml
<svg width="2048" height="2048" viewBox="0 0 2048 2048" xmlns="http://www.w3.org/2000/svg">
<path d="M1408 832q0-26-19-45t-45-19q-172 0-318 49.5t-259.5 134-235.5 219.5q-19 21-19 45 0 26 19 45t45 19q24 0 45-19 27-24 74-71t67-66q137-124 268.5-176t313.5-52q26 0 45-19t19-45zm512-198q0 95-20 193-46 224-184.5 383t-357.5 268q-214 108-438 108-148 0-286-47-15-5-88-42t-96-37q-16 0-39.5 32t-45 70-52.5 70-60 32q-30 0-51-11t-31-24-27-42q-2-4-6-11t-5.5-10-3-9.5-1.5-13.5q0-35 31-73.5t68-65.5 68-56 31-48q0-4-14-38t-16-44q-9-51-9-104 0-115 43.5-220t119-184.5 170.5-139 204-95.5q55-18 145-25.5t179.5-9 178.5-6 163.5-24 113.5-56.5l29.5-29.5 29.5-28 27-20 36.5-16 43.5-4.5q39 0 70.5 46t47.5 112 24 124 8 96z"/>
</svg>
```

![screen shot 2014-12-17 at 0 31 45](https://cloud.githubusercontent.com/assets/1935200/5464186/361e73c4-8585-11e4-9b76-452250444330.png)

**Comment by springmeyer** [comment]
Looks like the relative stroke size is interpreted relative to the size of the geometry. I'm no SVG expert, but I added `<path style="fill:rgb(0,0,255);stroke-width:10;stroke:rgb(255,0,0)"` to both SVGs and opened in Safari and confirmed this behavior. The stroke looks much bigger on the trees that the leaf.

**Comment by richterb** [comment]
Indeed, this was due to the size. I assumed the stroke would be drawn _after_ the SVG is resized (which wouldn't make much sense, now that I think about it), so I didn't think to look in that direction. Thanks a lot, it's going to spare me much struggle with my SVG :)

**Comment by springmeyer** [comment]
Cheers

**Comment by springmeyer** [comment]
@richterb - I've studied this issue more and am going to partially revert the above fix. So, adding properties like `marker-fill` will again have no effect on elements with `fill:none` (same for stroke). But I am going to keep the other behavior (which was also newly introduced in the above commit): when an element does not declare any fill or stroke properties then setting `marker-fill` or `marker-stroke` will impact the rendering. For more details follow https://github.com/mapnik/mapnik/issues/2609.

**Comment by richterb** [comment]
Thank you for the heads-up; in my own case it will still work as intended so it is fine, and I agree with your reasoning for the partial revert. I actually use the same strategy of using an invisible rect, but was doing the invisibility bit using `opacity:0` so the problem didn't hit me. :)

**Comment by springmeyer** [comment]
@richterb thanks, sounds good. Yes, also discussing using `opacity:0` or `visibility:hidden` as well to avoid things showing up that should not if I ever change my mind on this (and do allow `none` to be overridden): https://github.com/mapbox/maki/pull/202
