### ISSUE TITLE
Tirex compile error

### ISSUE THREAD

**Issue by Andrey-VI** [mapnik/mapnik-support#3]
https://gist.github.com/4131379

Debian Wheezy x64, Mapnik v. 2.1.0 installed from source, latest Tirex sources

**Comment by springmeyer** [comment]
I recall providing a patch to tirex on the Mapnik mailing list to fix this. Either that patch was applied and faulty or it was never applied. I can take a closer look on Monday.

**Comment by springmeyer** [comment]
are you using https://gist.github.com/3899892?

**Comment by Andrey-VI** [comment]
Oh, I missed this patch…
I have applied your updated patch and install tirex. Now something wrong with `tirex-backend-mapnik`. Logs extract:

```
Nov 27 15:02:26 carttiler tirex-backend-mapnik[27495]: cannot add /etc/tirex/renderer/mapnik/kosm.conf
Nov 27 15:02:26 carttiler tirex-backend-mapnik[27495]: no valid fonts could be loaded in FontSet 'book-fonts' in FontSet at line 5 of '/home/data/osm/mapnik-style/kosm.xml'
```

Stylesheet is OK. Seems that still some problems in tirex.

**Comment by springmeyer** [comment]
Could be something wrong with my patch as well. I only tested the compile, not runtime.

**Comment by springmeyer** [comment]
Can you try the patch again? https://gist.github.com/3899892

**Comment by Andrey-VI** [comment]
The new patch has solved the problem with fonts loading. Thanks!

No success in using tirex, however. But it seems to be a lack of experience.

**Comment by springmeyer** [comment]
great, so going to close this as the original issue is resolved.
