### ISSUE TITLE
  Mapnik master build failing on FreeBSD/PCBSD 10.1

### ISSUE THREAD

**Issue by PeterSprague** [mapnik/mapnik-support#33]
continuation of closed issue from Mapnik/issues
https://github.com/mapnik/mapnik/issues/2707

@springmeyer considers this a FreeBSD or particular machine issue, not a Mapnik bug.

When run suggested test.cpp, clang++ is used, and test program compiles and displays correctly.
When attempt to build Mapnik master on FreeBSd/PCBSD 10.1 using clang, many of the dependencies are not found: Z, icu, some boost, harfbuzz  

From console.log:
/usr/local/bin/clang35 -o .sconf_temp/conftest_10.o -c -std=c++11 -DSHAPE_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -Iinclude -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/local/include/libxml2 -I/usr/include .sconf_temp/conftest_10.cpp
/usr/local/bin/clang35 -o .sconf_temp/conftest_10 .sconf_temp/conftest_10.o -Lsrc -Lsrc/json -Lsrc/wkt -L/usr/local/lib -L/usr/lib -lpthread -lfreetype -lboost_system
/usr/bin/ld: //usr/lib/libc++.so.1: invalid DSO for symbol `_ZTVSt12length_error' definition
//usr/lib/libc++.so.1: could not read symbols: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: Configure: no

**Comment by springmeyer** [comment]
> /usr/local/bin/clang35

^^ that is wrong. It should be clang++.

**Comment by PeterSprague** [comment]
I understand the difference between c and c++, just wasn't clear on explicitly calling clang++
Thought clang35 would "wrap" clang++35 as needed.

built from ports clang36
Ran: scons configure CXX=/usr/local/bin/clang++36 => same console errors
see console.log gist: https://gist.github.com/PeterSprague/a180edc4b88719dcd946

**Comment by springmeyer** [comment]
> Thought clang35 would "wrap" clang++35 as needed.

No, that is not how things work.

The remaining errors in the config.log are:

> gcc: not found

Solve this by doing `./configure CC=clang` (or whatever C compiler you want to use).

> .sconf_temp/conftest_5.cpp:3:10: fatal error: 'unicode/unistr.h' file not found
> #include "unicode/unistr.h"

The compiler errors are now gone. Good. The new error above indicates you either don't have ICU installed or you need to point at it with ICU_LIBS and ICU_INCLUDES options.

> .sconf_temp/conftest_6.cpp:3:10: fatal error: 'harfbuzz/hb.h' file not found
> #include "harfbuzz/hb.h"

Same as ICU, harfbuzz needs to be installed or you need to point at it with HARFBUZZ_LIBS and HARFBUZZ_INCLUDES

**Comment by PeterSprague** [comment]
All "missing" dependencies were/are installed via pkg.
I  did "make deinstall" and "make reinstall clean"  for "missing" dependency ports.

Ran: scons configure CXX=/usr/local/bin/clang++36 CC=clang ICU_LIB=/usr/local/lib ICU_INCLUDES=/usr/local/include && make && make install

Shows no errors and configure completes, but make fails:
(from console)
All Required dependencies found!

Overwriting and re-saving file 'config.py'...
Will hold custom path variables from commandline and python config file(s)...
Checking for C header file Python.h... yes
Bindings Python version... 2.7
Python 2.7 prefix... /usr/local
Python bindings will install in... /usr/local/lib/python2.7/site-packages

Configure completed: run `make` to build or `make install`
make: "/usr/local/mapnik.git/Makefile" line 6: Missing dependency operator
make: "/usr/local/mapnik.git/Makefile" line 8: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/local/mapnik.git

Here are lines 6-8 of Makefile:
ifeq ($(JOBS),)
    JOBS:=1
endif
 Makefile gist: https://gist.github.com/PeterSprague/67eada86247d86cf2b0e

commented out lines 6-8 ifeq (from gmake manual: The default number of job slots is one, which means serial execution (one thing at a time). Handling recursive make invocations raises issues for parallel execution.

ran make
Error:
1 warning generated.
1 warning generated.
scons: done building targets.
python scons/scons.py -j --config=cache --implicit-cache --max-drift=1
usage: scons [OPTION] [TARGET] ...

SCons Error: option -j: invalid integer value: '--config=cache'
**\* Error code 2

Stop.

**Comment by PeterSprague** [comment]
Reversed comment out line 6-8
Follow Mapnik build directions here instead of main Mapnik build page:
https://github.com/mapnik/mapnik/wiki/UsingScons
aka don't use make directly on cmd line

Ran:
scons configure CXX=/usr/local/bin/clang++36 CC=/usr/local/bin/clang36 ICU_LIB=/usr/local/lib ICU_INCLUDES=/usr/local/include
python scons/scons.py

Error:
2 -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -ldl
/usr/bin/ld: cannot find -ldl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: **\* [src/libmapnik.so] Error 1
scons: building terminated because of errors.

And so the saga of just getting a working Mapnik v3 built to be able to reinstall Tilemill under FreeBSD 10.1 continues.
Sun is out and cherry trees are all blooming, so I guess I'll try and not scowl!

**Comment by PeterSprague** [comment]
Reverted to FreeBSd installed clang 3.4 under /usr/bin
vi /etc/make.conf -> revised/deleted previous clang usage
CC=/usr/bin/clang
CXX=/usr/bin/clang++
CPP=/usr/bin/clang-cpp

Reinstalled all dependencies via ports

Ran:
scons configure CXX=/usr/bin/clang++ CC=/usr/bin/clang ICU_LIB=/usr/local/lib ICU_INCLUDES=/usr/local/include

Same error as above:  /usr/bin/ld: can't find -ldl

Time for a different approach until mapnik v3.x builds on FreeBSd systems
Move back to mapnik v2.2.0_11 + node-mapnik v1.x
/usr/ports/graphics/mapnik
make deinstall -> make clean -> make install clean
npm install -g mapnik@1.x --build-from-source 
note: mapnik v1.x build directions missing mapnik@1.x, if follow doc attempts to build mapnik v3.x

10 minutes vs days.  Time to get back to mapping.

**Comment by PeterSprague** [comment]
git pull
git branch -> master aka V3

Ran: (as per: https://github.com/mapnik/mapnik/wiki/UsingScons)
python scons/scons.py configure CXX=clang++ CC=clang ICU_LIB=/usr/local/lib ICU_INCLUDES=/usr/local/include
compiles successfully -> requests to use make and make install
python scons/scons.py

Same error as above:  /usr/bin/ld: can't find -ldl

FreeBSD forum response: https://forums.freebsd.org/threads/building-mapnik-v3-and-node-mapnik-with-clang.50493/#post-282850
 /usr/bin/ld: can't find -ldl: ldl is a linuxism and must be removed on FreeBSD

**Comment by PeterSprague** [comment]
Simple fix: ln -s /usr/bin/clang++ /usr/local/bin/g++
See: https://github.com/mapbox/node-sqlite3/issues/250

**Comment by PeterSprague** [comment]
Where do I pull -ldl from for FreeBSD10?  SConstruct? Makefile?

See: https://forums.freebsd.org/threads/usr-bin-ld-cannot-find-ldl.5799/

**Comment by PeterSprague** [comment]
cd mapnik
grep -r ldl ./ 
yields
./include/mapnik/css_color_grammar.hpp:            ("oldlace", color(253, 245, 230))
./.mason/README.md:-L/Users/user/mason_packages/osx-10.10/libuv/0.11.29/lib -luv -lpthread -ldl
./utils/mapnik-config/mapnik-config:CONFIG_DEP_LIBS='  -lboost_filesystem -lboost_regex -lcairo -lpng -lproj -ltiff -lwebp -lxml2 -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -ldl'
Binary file ./scons/scons-local-2.3.4/SCons/Node/Alias.pyc matches
grep: ./src/libmapnik.so.3.0: No such file or directory

mapnik-config --dep-libs
yields
-lfreetype -lz -licuuc -lboost_filesystem -lboost_system -lboost_regex -lproj -lpng -ljpeg -ltiff -lxml2 -lboost_thread -licui18n -lcairo
aka no -ldl

python scons/scons.py configure ICU_LIB=/usr/local/lib ICU_INCLUDES=/usr/local/include HARFBUZZ_LIlocal/lib HARFBUZZ_INCLUDES=/usr/local/include
vi /utils/mapnik-config/mapnik-config
CONFIG_DEP_LIBS="
delete -ldl
python scons/scons.py
error as above
./utils/mapnik-config/mapnik-config is rewritten to include -ldl
mapnik-config --dep-libs
yields
-lfreetype -lz -licuuc -lboost_filesystem -lboost_system -lboost_regex -lproj -lpng -ljpeg -ltiff -lxml2 -lboost_thread -licui18n -lcairo
aka no -ldl

How to rewrite the dependency libs to not include ldl on make?

**Comment by springmeyer** [comment]
you can remove it by editing https://github.com/mapnik/mapnik/blob/master/src/build.py#L135

**Comment by PeterSprague** [comment]
Thanks. Compiling now, see what that gets me.

**Comment by PeterSprague** [comment]
commented out line #35 as above

scons configure ....
scons
scons install

no errors

test access/availability
python

> > > import mapnik
> > > no errors

mapnik-config and other bash scripts not working due to #!/bin/bash instead of #!/usr/local/bin/bash or preferably #!/bin/bash/env
ln -s /usr/local/bin/bash /bin/bash
fixed

mapnik-config -v -> 3.0.0-pre

Now to build node-mapnik@3.x
