### ISSUE TITLE
Problem defining some Symbolizers options in python

### ISSUE THREAD

**Issue by DemersM** [mapnik/mapnik-support#34]
Hi,

I would need help in defining some symbolizers options in python with mapnik 2.2.0. I am searching in the doc and in the API but cant find the right way to do it.

For TextSymbolizer.orientation the code below is not working:

```
t = mapnik.TextSymbolizer(mapnik.Expression('[column_a]'), 'DejaVu Sans Bold', 10, '#000000')
t.orientation = 22.5

>>>Boost.Python.ArgumentError: Python argument types in None.None(TextSymbolizerProperties, float) did not match C++ signature:
```

For the TextSymbolizer wrap-character option, is it possible to keep the wrapped character in the label? For instance, I would like to wrap this text at the char "-" to have this:

Sainte-
Brigitte-
de-
Laval

```
t = mapnik.TextSymbolizer(mapnik.Expression('[column_a]'), 'DejaVu Sans Bold', 10, '#000000')
t.wrap_character = ord("-")
```

For LineSymbolizer stroke dasharray, is it possible to append tuples of dash_length and gap_length in order to create combinations: Ex: - ---- - ---- -  
Using append dont seem to work. It does not returns error but the array stay with one element:

```
l = mapnik.LineSymbolizer()
l.stroke.dasharray = [(1,1)]
l.stroke.dasharray.append((4,1))
l.stroke.dasharray
>>> [(1.0,1.0)]
```

Thank you for your help,

**Comment by springmeyer** [comment]
> t.orientation = 22.5
> Boost.Python.ArgumentError: Python argument types in None.None(TextSymbolizerProperties, float) did not match C++ signature:

The `orientation` property is an expression object and in Mapnik 2.2.x this means it needs to be explicitly constructed like:

``` python
t.orientation = mapnik.Expression('22.5')
```

Keep in mind that if you use XML for styling you would be insulated from API complexities like this. So, I recommend templating XML to create styles on the fly over constructing in python.

> For the TextSymbolizer wrap-character option, is it possible to keep the wrapped character in the label? 

Yes, Mapnik 3.x added this feature: `repeat-wrap-chararacter`. For more details see https://github.com/mapnik/mapnik/issues/2333.

> For LineSymbolizer stroke dasharray, is it possible to append tuples of dash_length and gap_length in order to create combinations

``` python
>>> l = mapnik.LineSymbolizer(mapnik.Color('green'),0.1)
>>> l.stroke.add_dash(1,1)
>>> l.stroke.add_dash(4,1)
>>> l.stroke.get_dashes()
[(1.0, 1.0), (4.0, 1.0)]
```

**Comment by DemersM** [comment]
Thank you Dane!
