### ISSUE TITLE
Nik2Img: setting bbox and zoom level together doesn't work?

### ISSUE THREAD

**Issue by Andrey-VI** [mapnik/mapnik-support#4]
Command used: nik2img.py style.xml image.png -b 37.598494 55.745767 37.621711 55.755182 -z 17 -v
Terminal output here: https://gist.github.com/4337623
Note the steps 11—14 and 18. Strange values there.
Resulting image.png not with bbox (37.598494,55.745767,37.621711,55.755182), but seems to be with bbox (5.0932890358,-0.000894408328134,5.09603561778,0.000936646328296).

**Comment by springmeyer** [comment]
not sure it will fix by try `-d 256 256` to pass a square image (default is 600x400)

**Comment by springmeyer** [comment]
recall Mapnik's `aspect_fix_ratio` which will, by default, fix the aspect ratio of the map bounds to fit the image size (I think, can always mix this up)

**Comment by Andrey-VI** [comment]
But I want to set bbox and zoom level only, and Nik2Img should calculate image dimensions according to this values…
Maybe this is missing feature not the bug?

**Comment by springmeyer** [comment]
the default is `GROW_BBOX` (which means the bbox will be changed to fix the aspect ratio of the image): https://github.com/mapnik/mapnik/blob/master/src/map.cpp#L63

Sounds like you might want to do:

``` sh
nik2img.py --aspect-fix-mode=GROW_CANVAS ...
```

https://github.com/mapnik/mapnik/blob/master/src/map.cpp#L431-L485

**Comment by Andrey-VI** [comment]
My only problem is bbox. `-b` option in combination with `-z` option doesn't work.
With `-b 37.598494 55.745767 37.621711 55.755182 -z 17` or `-b 30 50 40 60 -z 17` I get

```
Step: 11 // --> Map extent: Box2d(5.0932890358,-0.00135217199224,5.09603561778,0.0013944099924)
Step: 12 // --> Map long/lat bbox: Box2d(5.0932890358,-0.00135217199224,5.09603561778,0.0013944099924)
Step: 13 // --> Map center: Coord(5.09466232679,2.11190000812e-05)
Step: 14 // --> Map long/lat center: Coord(5.09466232679,2.11190000812e-05)
Step: 15 // --> Map scale denominator: 4265.45909532
Step: 16 // --> Extent of all layers: Box2d(-180.000026,-89.000047438,190.189350653,89.000089676)
Step: 17 // --> Long/lat extent of all layers: Box2d(-180.000026,-89.000047438,190.189350653,89.000089676)
Step: 18 // --> Long/lat center of all layers: Coord(5.09466232679,2.11190000812e-05)
```

Why?

**Comment by springmeyer** [comment]
I'm not sure. I recommend you try digging around in the nik2img.py code (its just python) or write a pure python script to try to get done what you are after (as a comparative testcase)

**Comment by springmeyer** [comment]
I'm going to close this up. You've likely found a legitimate bug/oddity in nik2img, but its not a tool that I use/develop regularly.
