### ISSUE TITLE
Building Mapnik for PCBSD/FreeBSD10.1 recipe

### ISSUE THREAD

**Issue by PeterSprague** [mapnik/mapnik-support#40]
## Building Mapnik for PCBSD/FreeBSD10.1 notes

Current Mapnik from ports: V2.2.0_11
## Building Mapnik3 from Git master

References:
https://github.com/mapnik/mapnik
https://github.com/mapnik/mapnik/blob/master/INSTALL.md

as root, aka su

install ports:
node
npm
clang36
gcc48

vi /etc/make.conf
CXX=/usr/local/bin/clang36++
CC=/usr/local/bin/clang36
CPP=/usr/local/bin/clang36-cpp

ln -s /usr/local/bin/g++48 /usr/local/bin/g++
   see: https://github.com/mapbox/node-sqlite3/issues/250

install dependences:
boost-all w/ python
gdal
proj4
icu
py-icu
harfbuzz
scons

cd /usr/local
git clone https://github.com/mapnik/mapnik.git

cd mapnik
scons configure ICU_LIB=/usr/local/lib ICU_INCLUDES=/usr/local/include HARFBUZZ_LIBS=/usr/local/lib HARFBUZZ_INCLUDES=/usr/local/include
note - delete configure.py if want fresh config

Fix linux references - causes make errors
grep -r ./ ldl
./utils/mapnik-config/mapnik-config:CONFIG_DEP_LIBS='  -lboost_filesystem -lboost_regex -lcairo -lpng -lproj -ltiff -lwebp -lxml2 -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -ldl'

vi utils/mapnik-config/mapnik-config
goto CONFIG_DEP_LIBS=
delete -ldl

vi src/build.py
comment out line #135

scons
scons install

fix bash scripts not working because of ubuntu shebang
ln -s /usr/local/bin/bash /bin/bash

Test
python
">>>" import mapnik
mapnik-config -v -> version

**Comment by springmeyer** [comment]
#33
