### ISSUE TITLE
Cannot find -lboost_python-mt when installing python-mapnik

### ISSUE THREAD

**Issue by BoZenKhaa** [mapnik/mapnik-support#50]
I am installing python-mapnik on Xubuntu 14.04 after installing mapnik from source. Running "python setup.py install" gives me the following error:

/usr/bin/ld: cannot find -lboost_python-mt
/usr/bin/ld: cannot find -lboost_thread-mt
/usr/bin/ld: cannot find -lboost_system-mt
collect2: error: ld returned 1 exit status
error: command 'c++' failed with exit status 1

I installed boost with this command: 
sudo apt-get install build-essential python-dev python-setuptools libboost-python-dev libboost-thread-dev

I looked around python-mapnik but I have no idea how to pass the boost paths to the installer. How can I successfully install this?

**Comment by talaj** [comment]
https://github.com/mapnik/mapnik/issues/2987#issuecomment-122878987 seems like the same problem.

**Comment by BoZenKhaa** [comment]
Hello talaj, thank you very much for fast response. I tried [installing](http://stackoverflow.com/questions/4596492/usr-bin-ld-cannot-find-lboost-system-mt) libboost-all-dev, but I still get the same error when I run "python setup.py install". Do you have any idea what could be causing this?

**Comment by talaj** [comment]
Hi, according to http://askubuntu.com/a/486184 try to remove `-mt` from https://github.com/mapnik/python-mapnik/blob/d2a2afa3b5ee4b36df3aadb793784b5f248e8535/setup.py#L51-L53.

**Comment by BoZenKhaa** [comment]
Thank you very much! That worked for me. Cheers!

**Comment by talaj** [comment]
I would like to note that this is not a very clean solution. Better would be to set `BOOST_PYTHON_LIB`, `BOOST_SYSTEM_LIB` and `BOOST_THREAD_LIB` environment variables or somehow auto detect these names as this problem pops up often (https://github.com/mapnik/python-mapnik/issues/33).
