### ISSUE TITLE
dynamic datasource

### ISSUE THREAD

**Issue by xmcax** [mapnik/mapnik-support#53]
How can I provide psql datasource in datasource-settings.xml.inc dynamically?

What I'm trying to achieve is to create a database and mapnik in a separate docker containers. 
To make it work I need to be able to provide the db: host, port, dbname & user using env variable.

**Comment by springmeyer** [comment]
@xmcax - the easiest solution is to just remove all those variables from the XML. Then they will be picked up from the environment if you set in them correctly for `libpq`: http://www.postgresql.org/docs/9.3/static/libpq-envars.html

**Comment by xmcax** [comment]
Works like a charm, thanks:)
