### ISSUE TITLE
Problem with compilation on CentOS 7

### ISSUE THREAD

**Issue by mike-ainsel** [mapnik/mapnik-support#54]
Hello everyone, i have problem with compilation python module on CentOS7, then i'm running 
python setup.py build
i received next error, c++: erroe: recordcc-switches: no such file or directory.
I was trying to find a related information, but no luck, only that this might mean, that i have't compatible with c++11 standard c++ compiler
But this is odd, because on that machine i had successfully build a boost c++ library (version v1.59) and after that mapnik (v3.0.5), when i had run a ./configure, one of the lines he had printed was:
Checking if compiler (c++) supports -std=c++11 flag... (cached) yes

My emviroment: CentOS7 minimal, libraries need for mapnik v3.0.5, epel-repo, pg93-repo.
g++   -  4.8.3 

What i'm doing wrong ? Maybe i'm missing some libraries or something else ?
Thanks in advance

**Comment by lujop** [comment]
I've exactly the same problem.
I also used CentOS7, compiled Mapnik 3.0.5 from sources with centos provided dependencies except for Boost that was manually com0piled from 1.59.

Do you make any progress on that mike?

**Comment by mike-ainsel** [comment]
Nope, still nothing :(

**Comment by springmeyer** [comment]
fixed by https://github.com/mapnik/python-mapnik/issues/54
