### ISSUE TITLE
ImportError: No module named mapnik

### ISSUE THREAD

**Issue by gunyakov** [mapnik/mapnik-support#55]
All compilation and installation passed. But when I try to run python ./rundemo.py i receive 
Traceback (most recent call last):
  File "./rundemo.py", line 26, in <module>
    import mapnik
ImportError: No module named mapnik

Can you help me???

**Comment by talaj** [comment]
Most likely your Mapnik python module is not installed on search path for python module files. You can set it by [`PYTHONPATH`](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH).

**Comment by springmeyer** [comment]
See https://github.com/mapnik/python-mapnik for more details of how to install python-mapnik.
