### ISSUE TITLE
trouble building mapnik from source on Ubuntu 14.04

### ISSUE THREAD

**Issue by KlemenSpruk** [mapnik/mapnik-support#59]
I have installed all needed dependencies so when i run ./configure i get no warning.

Mapnik source code is version 3.0.9.

![screenshot from 2016-01-06 11 50 01](https://cloud.githubusercontent.com/assets/8971677/12140907/a3ffada2-b46b-11e5-8345-89014fc44b11.png)

I ran make commands and mapnik is successfully builded.
When I test it in python console via command: python -c "import mapnik;print mapnik.**file**"
I get 
![screenshot from 2016-01-06 11 51 58](https://cloud.githubusercontent.com/assets/8971677/12140944/dee0638a-b46b-11e5-84a8-6bb964e3ed88.png)

This is ok.

When I run python executable script wiith input files i get error:
![screenshot from 2016-01-06 11 53 23](https://cloud.githubusercontent.com/assets/8971677/12140969/111d4a7a-b46c-11e5-9e6e-a7e795603e36.png)

My python script (mapnik2.py):
# !/usr/bin/env python

import mapnik

m = mapnik.Map(600, 300)
m.background = mapnik.Color('steelblue')
s = mapnik.Style()
r = mapnik.Rule()
polygon_symbolizer = mapnik.PolygonSymbolizer(mapnik.Color('#f2eff9'))
r.symbols.append(polygon_symbolizer)
line_symbolizer = mapnik.LineSymbolizer(mapnik.Color('rgb(50%,50%,50%)'), 0.1)
r.symbols.append(line_symbolizer)
s.rules.append(r)
m.append_style('My Style', s)
ds = mapnik.Shapefile(file='/var/www/mapnik_klemen_doc/wbshp.shp')
layer = mapnik.Layer('world')
layer.datasource = ds
layer.styles.append('My Style')
m.layers.append(layer)
m.zoom_all()
mapnik.render_to_file(m, 'world.png', 'png')
print "rendered image to 'world.png'"

Does anyone have any idea what could be the problem?

**Comment by springmeyer** [comment]
> Unary dispatch: FAIL mapnik::value_holder

That looks like a bug. Can you share what compiler version you used to compile Mapnik?

This sounds a bit mysterious and like https://github.com/mapnik/node-mapnik/issues/573

/cc @artemp

**Comment by KlemenSpruk** [comment]
![image](https://cloud.githubusercontent.com/assets/8971677/12741738/75b488e0-c97f-11e5-8913-f29d67551e94.png)

**Comment by artemp** [comment]
@KlemenSpruk - from your screenshot I see you have `4.8.2` and `4.8.4`, it's not clear which one was used to compile mapnik. 

As a wild guess try setting CXX option at configure step to force `4.8.4'

```
./scons/scons.py configure CXX="g++-4.8" CC="gcc-4.8"
```
