### ISSUE TITLE
estimation of extent during load_map using datasource type "sqlite"

### ISSUE THREAD

**Issue by schwalbe** [mapnik/mapnik-support#6]
we use datasource type=sqlite and find, it takes a long time to load_map(). After looking round information given by MAPNIK_STATS, the most time costs are caused by determination of extent in function sqlite_datasource::bind() (not sure, but from "sqlite_resultset::execute_query SELECT MIN(xmin), MIN(ymin), MAX(xmax), MAX(ymax) FROM "idx_table"" ).

If extent of table is not given, it will be determined by function sqlite_ultils::detect_extent(...).  process is

```
if (spatial index exists)
    execute query "SELECT MIN(xmin), MIN(ymin), MAX(xmax), MAX(ymax) FROM index_table"
else if( metadata table is given)
    execute query "SELECT xmin, ymin, xmax, ymax FROM metadata talbe"
else
    calculate extent from table
```

Now my question is: query from "metadata table" is faster than "index_table", because there are large numbers of  records in index_table(in my case). why not query metadata table at first?

**Comment by artemp** [comment]
@schwalbe - fixed in  bba0b61dfcfde94498000da6e8c5d5248037afa2 - thanks for catching this!
