### ISSUE TITLE
PostGIS datasource: closing connections

### ISSUE THREAD

**Issue by mbonnefoy** [mapnik/mapnik-support#61]
Hi there,

For test purposes, I need to close the connection as soon I am done with it.
Is there a way to handle that need gracefully? I could not find one.

Thanks,
Matthieu

**Comment by springmeyer** [comment]
Yes, `persist_connection:false`: https://github.com/mapnik/mapnik/blob/33be145be92837e19088ede69652398807211759/plugins/input/postgis/postgis_datasource.cpp#L87 | https://github.com/mapnik/mapnik-reference/blob/master/3.0.9/datasources.json#L331-L337
