### ISSUE TITLE
Mapnik CSV plugin

### ISSUE THREAD

**Issue by kozyr** [mapnik/mapnik-support#62]
I'm using Mapnik and tirex to generate tiles from CSV. Works fine, but it seems like the CSV is re-read for each tile, which is wasteful. Looking at the CSV plugin, it seems like it supports an on-disk index - any docs/info on how to generate it?

**Comment by wilhelmberg** [comment]
From `mapnik@3.0.8` on there's a utility called `mapnik-index`.
https://github.com/mapnik/mapnik/blob/master/CHANGELOG.md#308

If you build from source you should find `mapnik-index` in `util/mapnik-index/`.
