### ISSUE TITLE
Python binding DLL load failed on Win10/64 - mapnik 2.2.0

### ISSUE THREAD

**Issue by stefanborchardt** [mapnik/mapnik-support#67]
I have trouble getting the Python binding to work on Win10/64. 
I unzipped the download and set the paths. Mapnik-config works, I have set the PYTHONPATH and still I get 
File "C:\mapnik-v2.2.0\python\2.7\site-packages\mapnik__init__.py", line 69, in <module>     from _mapnik import \* ImportError: DLL load failed: %1 is not a valid Win32 application.
in both Spyder and command window.

**Comment by wilhelmberg** [comment]
Looks like you are using Python 64bit.
The mapnik 2.2.0 package is 32bit.

Try with Python 2.7 32bit and let me know if it works.

**Comment by stefanborchardt** [comment]
Thank you for making sense of the error message. You are right, my Python is 64bit. I apologize for not trying a parallel install of Python/32, but waiting for the Mapnik 3 binaries.

**Comment by wilhelmberg** [comment]
@stefanborchardt great, thanks for getting back.

If you are feeling adventurous you might want to check out the latest `mapnik@3.x` 64bit SDK:
https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-v3.0.10-x64-14.0.7z

Be warned that the Python bindings are lagging behind a bit and are not yet thoroughly tested and might even produce some strange results or not work as expected.
