### ISSUE TITLE
Rendering image data

### ISSUE THREAD

**Issue by ndimiduk** [mapnik/mapnik-support#7]
I'm trying to replicate the results of mapnik.render_to_file() using mapnik.Image.tostring() and Python native file operations. The result using the latter is a valid PNG but it is not byte-identical to that produced using the former. It also appears to not contain my map data. Any assistance is appreciated.

The former:

```
mapnik.render_to_file(map, 'map.png', 'png')
```

The latter:

```
im = mapnik.Image(256,256)
mapnik.render(map,im)
buff = im.tostring('png')
with open('map2.png', 'wb') as f:
    f.write(buff)
```

For context, I need to write out the image data as text to stdout so that it can be read in again by another process for further processing. Ideally, I could do something like `mapnik.render_to_file(map, sys.stdout, 'png')`, however, this appears to not be possible with the current API.

Thanks,
-n

**Comment by springmeyer** [comment]
Interesting. They should be identical. In testing are you remembering to set your map to the correct bounds with 'zoom_to_box'? If your find that an identical map truly renders differently then there must be some subtle bug in the conversion of bytes to a python string that I can look into. 

Also writing to stdout in pure c++ land would be doable. If this is faster/if there is overhead in going through python, then we could consider opening an API for this.

**Comment by ndimiduk** [comment]
That was the interface I expected, though realistically won't work for my
project. I think I'll need to base64 encode the image data and print it
along with metadata to stdout.

**Comment by ndimiduk** [comment]
That said, I think the interface I would be looking for looks something like:

```
mapnik.render(map, im)
print "%s\t%s" % (some_metadata, base64encode(im.data))
```

Is this possible with mapnik today? I'm using mapnik-2.1.0 via homebrew, though I plan to deploy on a linux variant.

**Comment by springmeyer** [comment]
This should work:

``` py
import mapnik
import base64
# code to set up map and image, etc
mapnik.render(map,im)
sys.stdout.write("%s\t%s" % (some_metadata, base64.encode(im.tostring('png'))
```

Again, I think if your image is coming out blank then its likely some other problem than the encoding of the png.

Can you try adding

`im.save('test.png')` to see if that has your map data?

Also try `open('test.png','wb').write(im.tostring('png'))`

**Comment by ndimiduk** [comment]
It appears I cannot save a map to a file and then immediately render it to an image. This seems to be the cause of my broken second file. That is, don't do this, as map2.png is broken:

```
map = init_map(stdin)
map.zoom_all()
mapnik.render_to_file(map, 'map.png', 'png')
im = mapnik.Image(256,256)
mapnik.render(map,im)
buff = im.tostring('png')
with open('map2.png', 'wb') as f:
    f.write(buff)
```

**Comment by springmeyer** [comment]
Extremely odd. Never seen anything like this before. Can you post or email me a full testcase so I can try to replicate tomorrow?

Alternatively I wonder if this is some kind of build/compile problem. I saw you used homebrew to install Mapnik. You might try building Mapnik head instead like 'brew install mapnik --HEAD' to see if that makes any difference.

**Comment by springmeyer** [comment]
ping

**Comment by ndimiduk** [comment]
Strange. I created a miniature version and cannot repro either.

https://gist.github.com/ndimiduk/5183913

**Comment by springmeyer** [comment]
@ndimiduk - thinking about this more, I bet the problem is simply that your custom datasource (I had forgot you were rolling your own) must be saving state somehow such that the second time it is accessed, no features are returned. Either that or there is a bug in the python plugin itself whereby some iterator is not being reset properly. I've not used the python plugin much so that is just a guess.

**Comment by ndimiduk** [comment]
I was wondering if I'd screwed up the datasource, but i was expecting an off-by-one error, not a garbled image. Oh well. Thanks for the help!
