### ISSUE TITLE
Issue displaying to layers using XML stylesheet

### ISSUE THREAD

**Issue by rheh** [mapnik/mapnik-support#76]
I'm trying to use mapnik to draw a line path over a layer of countries.  The problem I'm having is that both work on there own, but, not together.  Here is my style:

```
<?xml version="1.0" encoding="UTF-8"?>
<Map srs="+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs" background-color="white">

  <Style name="countries">
    <Rule>
      <PolygonSymbolizer fill="rgb(255, 228, 193)" clip="false"/>
      <LineSymbolizer stroke="rgba(77, 163, 148, 0.5)" stroke-width="1" />
    </Rule>

  </Style>

  <Style name="points">
    <Rule>
      <LineSymbolizer  clip="false" stroke="rgba(77, 163, 148, 1)" stroke-width="2" />
    </Rule>
  </Style>

  <Layer status="on" name="world">
    <StyleName>countries</StyleName>
    <Datasource>
      <Parameter name="file">../data/world_merc.json</Parameter>
      <Parameter name="type">geojson</Parameter>
    </Datasource>
  </Layer>

  <Layer status="on" name="routeLine" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
    <StyleName>points</StyleName>
    <Datasource>
      <Parameter name="file">../data/routepath.json</Parameter>
      <Parameter name="type">geojson</Parameter>
    </Datasource>
  </Layer>

</Map>
```

With both I get:

![map-merc](https://cloud.githubusercontent.com/assets/1724245/16669763/1bcd0346-444c-11e6-9e9e-c12a411e1cd7.png)

And if I remove the map layer from the XML I get:

![map](https://cloud.githubusercontent.com/assets/1724245/16669758/14042004-444c-11e6-955d-5349c6a2913b.png)

Can anyone see where I am going wrong?

**Comment by talaj** [comment]
Are both input projections correct? Isn't the line path just too short compared to whole world?

**Comment by rheh** [comment]
Thanks - I think it is projection related - I spent a few more hours on it yesterday.  If I remove the Lambert 93 srs from the map it works; however, it is this projection that I want - not mercator.  The data in the countries json is that from the demo projects which I believe is merc projection; thus, I though putting the srs for Lamert 93 on the map would do the necessary transform.  But it does n't.

This style-sheet work:

```
<?xml version="1.0" encoding="UTF-8"?>
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over" background-color="white">

  <Style name="countries">
    <Rule>
      <PolygonSymbolizer fill="rgb(255, 228, 193)" clip="false"/>
      <LineSymbolizer stroke="rgba(77, 163, 148, 0.5)" stroke-width="1" />
    </Rule>

  </Style>
  <Style name="points">
    <Rule>
      <LineSymbolizer  clip="false" stroke="rgba(77, 163, 148, 1)" stroke-width="2" />
    </Rule>
  </Style>

  <Layer status="on" name="world">
    <StyleName>countries</StyleName>
    <Datasource>
      <Parameter name="file">../data/world_merc.json</Parameter>
      <Parameter name="type">geojson</Parameter>
    </Datasource>
  </Layer>

  <Layer status="on" name="routeLine" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
    <StyleName>points</StyleName>
    <Datasource>
      <Parameter name="file">../data/routepath.json</Parameter>
      <Parameter name="type">geojson</Parameter>
    </Datasource>
  </Layer>

</Map>

```

However, as stated I above I was a Lamert 93 projection.  How would I achieve  this?

Thanks

Ray

**Comment by talaj** [comment]
Thanks for the info, I will try to reproduce it.

**Comment by rheh** [comment]
I can supply the geojson files if required?

**Comment by talaj** [comment]
Why are you insist on Lambert-93? According to [spatialreference.org](http://spatialreference.org/ref/epsg/rgf93-lambert-93/), Lambert-93 is designed for the area of France. I think using such projection for the whole world is not good idea and can cause distortion of geometries in such way they can fall off rendering bounds.

**Comment by rheh** [comment]
It's the preferred projection in the Aviation world Pilots use aeronautical charts based on LCC because a straight line drawn on a Lambert conformal conic projection approximates a great-circle route between endpoints for typical flight distances.

**Comment by talaj** [comment]
> I can supply the geojson files if required?

I could reproduce it, thanks.

I'm testing with following XML.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Map srs="+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs" background-color="white">
    <Parameters>
        <Parameter name="sizes">1024,768</Parameter>
    </Parameters>

    <Style name="countries">
        <Rule>
            <PolygonSymbolizer fill="rgb(255, 228, 193)" clip="false"/>
            <LineSymbolizer stroke="rgba(77, 163, 148, 0.5)" stroke-width="1" />
        </Rule>

    </Style>
    <Style name="points">
        <Rule>
            <LineSymbolizer  clip="false" stroke="rgba(77, 163, 148, 1)" stroke-width="2" />
        </Rule>
    </Style>

    <Layer status="on" name="world">
        <StyleName>countries</StyleName>
        <Datasource>
            <Parameter name="file">world_merc.json</Parameter>
            <Parameter name="type">geojson</Parameter>
        </Datasource>
    </Layer>

    <Layer status="on" name="routeLine" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        <StyleName>points</StyleName>
        <Datasource>
            <Parameter name="inline">
                wkt
                "LINESTRING(-0.260977596045 51.550861001, 2.33179584146 48.8514328748, 6.90210834146 50.9733894467, 13.4939052165 52.4972462654, 20.9646083415 52.2558018565, 27.4685145915 53.9959037304, 37.5759364665 55.7899327576)"
            </Parameter>
            <Parameter name="type">csv</Parameter>
        </Datasource>
    </Layer>

</Map>
```
The line path is missing on the output:

![_test-1024-768-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/16689880/53f841ca-4525-11e6-9a26-d95c267d8cec.png)

I maybe found related bug. `buffered_query_ext` in [this](https://github.com/mapnik/mapnik/blob/5c0aa52d22f5e159970edca4d5b16912fc801e4b/include/mapnik/feature_style_processor_impl.hpp#L284) condition is in wrong projection due to [this reprojection](https://github.com/mapnik/mapnik/blob/5c0aa52d22f5e159970edca4d5b16912fc801e4b/include/mapnik/feature_style_processor_impl.hpp#L273) a couple of lines above.

The following patch kind of solved the missing line path:
```diff
diff --git a/include/mapnik/feature_style_processor_impl.hpp b/include/mapnik/feature_style_processor_impl.hpp
index 89e0c3a..d5f6413 100644
--- a/include/mapnik/feature_style_processor_impl.hpp
+++ b/include/mapnik/feature_style_processor_impl.hpp
@@ -269,11 +269,13 @@ void feature_style_processor<Processor>::prepare_layer(layer_rendering_material
     bool fw_success = false;
     bool early_return = false;

+    box2d<double> buffered_query_ext_copy = buffered_query_ext;
+
     // first, try intersection of map extent forward projected into layer srs
-    if (prj_trans.forward(buffered_query_ext, PROJ_ENVELOPE_POINTS) && buffered_query_ext.intersects(layer_ext))
+    if (prj_trans.forward(buffered_query_ext_copy, PROJ_ENVELOPE_POINTS) && buffered_query_ext_copy.intersects(layer_ext))
     {
         fw_success = true;
-        layer_ext.clip(buffered_query_ext);
+        layer_ext.clip(buffered_query_ext_copy);
     }
     // if no intersection and projections are also equal, early return
     else if (prj_trans.equal())

```


![_test-1024-768-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/16688868/7024b1ee-4520-11e6-8767-37cadb40dba7.png)

However, this is how it looks in Mercator, the line path connects London with Moscow, which was the intention:
![_test-1024-768-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/16689917/8904426a-4525-11e6-84a5-552f207ef63c.png)

My question is, why is the `countries` layer projected the same way with LCC and Mercator?

**Comment by talaj** [comment]
Yeah, it works well now, when I set `srs` of the `world` layer and rendering just bbox of Lambert-93 (-357823.2365, 6037008.6939, 1313632.3628, 7230727.3772):

``` xml
<Layer status="on" name="world" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">

```

![_test-1024-768-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/16690678/4bc3557c-4529-11e6-8a61-a5301ec2cb1a.png)

Bigger bbox:
![_test-1024-768-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/16690806/f99c94c4-4529-11e6-92f8-6b99721e1a6a.png)

**Comment by rheh** [comment]
Many thanks for the assistance.  Is this with the LLC projection on the map? As mine still only work with the merc projection on the map layer.

**Comment by talaj** [comment]
>  Is this with the LLC projection on the map? As mine still only work with the merc projection on the map layer.

Yes, this is complete style I have used:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Map srs="+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs" background-color="white">
    <Style name="countries">
        <Rule>
            <PolygonSymbolizer fill="rgb(255, 228, 193)" clip="false"/>
            <LineSymbolizer stroke="rgba(77, 163, 148, 0.5)" stroke-width="1" />
        </Rule>
    </Style>

    <Style name="points">
        <Rule>
            <LineSymbolizer  clip="false" stroke="rgba(77, 163, 148, 1)" stroke-width="2" />
        </Rule>
    </Style>

    <Layer status="on" name="world" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
        <StyleName>countries</StyleName>
        <Datasource>
            <Parameter name="file">world_merc.json</Parameter>
            <Parameter name="type">geojson</Parameter>
        </Datasource>
    </Layer>

    <Layer status="on" name="routeLine" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        <StyleName>points</StyleName>
        <Datasource>
            <Parameter name="inline">
                wkt
                "LINESTRING(-0.260977596045 51.550861001, 2.33179584146 48.8514328748, 6.90210834146 50.9733894467, 13.4939052165 52.4972462654, 20.9646083415 52.2558018565, 27.4685145915 53.9959037304, 37.5759364665 55.7899327576)"
            </Parameter>
            <Parameter name="type">csv</Parameter>
        </Datasource>
    </Layer>

</Map>

```

**Comment by rheh** [comment]
Thanks @talaj it work just fine now.
