### ISSUE TITLE
Applying a comp-op wiith a background-image and background-color 

### ISSUE THREAD

**Issue by skorasaurus** [mapnik/mapnik-support#8]
I'm trying to apply a comp-op to my background image using a background-color. 

As shown in http://i.imgur.com/usB55Mb.jpg, I'm working on a coastline and the only way that I know how to set the color of the water for a coastline is to do map { background-color: hexcode; } 

I'm using a background-image and then using a comp-op (overlay) to apply to other layers (like land) in the picture. 

But how would I apply this comp-op to the map's background color ? (or vice-versa ?)

**Comment by springmeyer** [comment]
this is now landed in upcoming Mapnik 2.3.x
