### ISSUE TITLE
Rendering artifacts with OSM data & Arctic projections (w/ demo)

### ISSUE THREAD

**Issue by brucecrevensten** [mapnik/mapnik-support#83]
We are running an OSM server, assembled mostly according to directions [here](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/), but with Mapnik 3.0.10.  Our data source is a small world subset containing just Alaska, obtained [here](http://download.geofabrik.de/north-america/us/alaska.html).  We use MapProxy as a WMS endpoint, configured to talk directly with Mapnik for our layers of interest.  Our stylesheet is [here](https://github.com/ua-snap/Alaska-CartoCSS) and is a slightly-modified version of the HOT stylesheet.

There are what appear to be large rendering areas -- long, narrow horizontal polygons, rendering as water, throughout the map at varying zoom levels.

I made a [demonstration page](https://ua-snap.github.io/map-osm-examples/) with maps in EPSG:3338, EPSG:3572, and EPSG:3857.  The first two exhibit the rendering errors.

I'm new enough to this stack of tech that I'm unclear on whether I'm seeing an error in OSM data (if so, why not present in 3857?), a misconfiguration that is tripping up Mapnik (again, why no problem in 3857), or some other issue.

Let me know if I can provide additional details or information.

**Comment by lightmare** [comment]
I've seen this in the past, but never figured out what was the cause. The first thing I'd blame was polygon clipping, but iirc we had clipping off. Next, I'd try simplifying the water polygons a lot, just to see if that helps.

**Comment by brucecrevensten** [comment]
Thanks to some folks on the OSM IRC channel, I've got this working.  The problem here was that one of the source data layers needed to be using the unspilt, rather than the split, polygons.  Using [the un-split WGS84 polygon data](http://data.openstreetmapdata.com/land-polygons-complete-4326.zip) worked.

Almost certainly not a rendering error in Mapnik, just bad input!
