### ISSUE TITLE
Mapnik configure cannot find boost libs

### ISSUE THREAD

**Issue by egoddard** [mapnik/mapnik-support#9]
./configure fails due to being unable to locate the boost libs and headers installed from repos on opensuse 12.3. Even when passing the BOOST_HEADERS path, scons searches the default /usr/include. config.log and configure output at https://gist.github.com/egoddard/62e5457b471f78346da4.

**Comment by springmeyer** [comment]
looks like the problem is that libraries lack proper soname symlinks. So `/usr/lib/libboost_regex.so.1.49.0` exists but mapnik tries to link to `/usr/lib/libboost_regex.so.1.49`.

**Comment by springmeyer** [comment]
@egoddard said on IRC that the problem turned out to be a missing boost package:

> 18:34:25 <EricG> hmmm..I didn't have boost-devel-32bit installed. After installing that, it configured.

http://mapnik.dbsgeo.com/mapnik_logs/2013/03/26/
