### ISSUE TITLE
<symbol>/<use> not supported in SVG PointSymbolizer?

### ISSUE THREAD

**Issue by hholzgra** [mapnik/mapnik-support#90]
looks as if <symbol>s referenced by <use> are not supported when using
SVG images with PointSymbolizer / ShieldSymbolizer?

Is this indeed an unsupported SVG feature, or am I simply doing it wrong?

As an example I rendered a GPX path with Waypoints, using a SVG that has
a black square background and a smaller white square foreground.

The style for waypoings is as simple as possible:

  <Style name="point">
    <Rule>
      <PointSymbolizer file="marker.svg" />
    </Rule>
  </Style>

With a "simple" SVG the result looks as expected:

  http://osm-baustelle.de/simple.png

but when the white square is defined as a SVG <symbol> and referenced
by a <use> xlink only the black background square gets rendered:

  http://osm-baustelle.de/symbol-use.png

The actual SVG files look exactly the same in the browser:

  http://osm-baustelle.de/simple.svg
  http://osm-baustelle.de/symbol-use.svg

In this example it would be easy to just replace the <use> with the
actual path, in the actual use case the <symbol>s in the SVG are
glyph paths auto-generated by Cairo/Pango which are referenced with
an x/y offset, and potentially multiple times.

So post-processing the auto-generated SVG images would be a bit more
complicated than just moving lines to a different part of the file.

**Comment by springmeyer** [comment]
`<symbol>` and `<use>` are not currently supported, see https://github.com/mapnik/mapnik/issues/763 and https://github.com/mapnik/mapnik/issues/3181

**Comment by artemp** [comment]
@hholzgra - Initial support for `<use>` element added in https://github.com/mapnik/mapnik/tree/svg-strict-parsing (https://github.com/mapnik/mapnik/issues/763). As a side-effect `<symbol>` elements are rendered too (at least in case of http://osm-baustelle.de/symbol-use.svg when `<symbol>` is inside `<def></def>`) but this still needs more work. Leaving this issue open to track `<symbol>` support.

/cc @springmeyer

**Comment by springmeyer** [comment]
> but this still needs more work. Leaving this issue open to track <symbol> support.

@artemp can you share what still needs work / is unsupported?

Also, should we track achieving full `<symbol>` here or https://github.com/mapnik/mapnik/issues/3181?

**Comment by artemp** [comment]
`<symbol>` needs implementing. The fact that it sometimes works already is just a byproduct of implementing `<use>`.

 Lets move this to mapnik/mapnik#3181 , closing.
/cc @springmeyer
