### ISSUE TITLE
RasterColorizer C++ usage

### ISSUE THREAD

**Issue by am2222** [mapnik/mapnik-support#92]
Hi,
I am going to use gdal plugin to open and show a raster file. Here is my style
````
// raster dem
        feature_type_style dem;
        {
            rule r;
            {
                raster_symbolizer raster_sym;
		//colorizer
		raster_colorizer cl;
				colorizer_stop st;
				st.set_color(color(127, 200, 100, 250));
				st.set_value(900);
				cl.add_stop(st);
				colorizer_stop st1;
				st1.set_color(color(127, 140, 100, 250));
				st1.set_value(1500);
				colorizer_mode mod;
				mod.from_string("discrete");
				st1.set_mode(mod);
				cl.add_stop(st1);

				colorizer_stop st2;
				st2.set_color(color(250, 140, 100, 250));
				st2.set_value(2000);
				//colorizer_mode mod;
				//mod.from_string("discrete");
				st2.set_mode(mod);
				cl.add_stop(st2);
		//put(raster_sym, mapnik::keys::colorizer, cl);
                put(raster_sym,keys::opacity,"1");
                put(raster_sym,keys::scaling,"bilinear");
                put(raster_sym,keys::mode,"normal");
                r.append(std::move(raster_sym));
            }
            dem.add_rule(std::move(r));
        }

        m.insert_style("dem", std::move(dem));
````

As far as I am concerned this style should work but in this line 
`put(raster_sym, mapnik::keys::colorizer, cl);`
I get this error
`In file included from include/mapnik/rule.hpp:28:
include/mapnik/symbolizer_base.hpp:109:11: error: no matching constructor for
      initialization of 'value_base_type' (aka 'mapbox::util::variant<bool,
      long, mapnik::enumeration_wrapper, double, std::basic_string<char>,
      mapnik::color, std::shared_ptr<mapbox::util::variant<mapnik::value_null,
      bool, long, double, icu_57::UnicodeString, mapnik::attribute,
      mapnik::global_attribute, mapnik::geometry_type_attribute,
      mapbox::util::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate>
      >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus>
      >,
      mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus>
      >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult>
      >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::div>
      >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod>
      >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::less>
      >,
      mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal>
      >,
      mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater>
      >,
      mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal>
      >,
      mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to>
      >,
      mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to>
      >,
      mapbox::util::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not>
      >,
      mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and>
      >,
      mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or>
      >, mapbox::util::recursive_wrapper<mapnik::regex_match_node>,
      mapbox::util::recursive_wrapper<mapnik::regex_replace_node>,
      mapbox::util::recursive_wrapper<mapnik::unary_function_call>,
      mapbox::util::recursive_wrapper<mapnik::binary_function_call> > >,
      std::shared_ptr<std::vector<mapbox::util::variant<std::basic_string<char>,
      mapnik::attribute>,
      std::allocator<mapbox::util::variant<std::basic_string<char>,
      mapnik::attribute> > > >,
      std::shared_ptr<std::vector<mapnik::detail::transform_node,
      std::allocator<mapnik::detail::transform_node> > >,
      std::shared_ptr<mapnik::text_placements>, std::vector<std::pair<double,
      double>, std::allocator<std::pair<double, double> > >,
      std::shared_ptr<mapnik::raster_colorizer>,
      std::shared_ptr<mapnik::group_symbolizer_properties>,
      mapnik::font_feature_settings>')
        : value_base_type(U(std::forward<T>(obj)))
          ^               ~~~~~~~~~~~~~~~~~~~~~~~
include/mapnik/symbolizer.hpp:264:35: note: in instantiation of function
      template specialization 'mapnik::detail::strict_value::strict_value<const
      mapnik::raster_colorizer &, const mapnik::raster_colorizer &>' requested
      here
            sym.properties[key] = val;
                                  ^
include/mapnik/symbolizer.hpp:411:34: note: in instantiation of member function
      'mapnik::detail::put_impl<mapnik::raster_colorizer, false>::apply'
      requested here
    detail::put_impl<T, enum_ >::apply(sym, key, val);
                                 ^
demo/c++/rundemo.cpp:179:3: note: in instantiation of function template
      specialization 'mapnik::put<mapnik::raster_colorizer>' requested here
                put(raster_sym, mapnik::keys::colorizer, cl);
                ^
deps/mapbox/variant/include/mapbox/variant.hpp:606:20: note: candidate
      constructor not viable: no known conversion from 'const
      mapnik::raster_colorizer' to 'mapbox::util::no_init' for 1st argument
    VARIANT_INLINE variant(no_init) noexcept
                   ^
`

**Comment by talaj** [comment]
Hi! I think you should `put()` `raster_colorizer_ptr` rather than `raster_colorizer`. See [map_parser::parse_raster_symbolizer](https://github.com/mapnik/mapnik/blob/a3247c8dce50be1028fdfb9836f7a63471dc6542/src/load_map.cpp#L1382) for inspiration.

**Comment by am2222** [comment]
@talaj  thanks for your answer, But I can not find any method to add stop. How can I add stops then?

**Comment by am2222** [comment]
I used this code but It still returns error
`raster_colorizer_ptr cl;
				colorizer_stop st;
				st.set_color(color(127, 200, 100));
				st.set_value(900);
				cl->add_stop(st);
			 `

**Comment by talaj** [comment]
Still the same error? I can compile and run this without any problem:

```c++
#include <mapnik/raster_colorizer.hpp>
#include <mapnik/symbolizer.hpp>
#include <mapnik/symbolizer_utils.hpp>

main()
{
    mapnik::raster_symbolizer raster_sym;
    mapnik::raster_colorizer_ptr colorizer = std::make_shared<mapnik::raster_colorizer>();

    mapnik::colorizer_stop stop;
    stop.set_color(mapnik::color(127, 200, 100));
    stop.set_mode(mapnik::COLORIZER_LINEAR);
    stop.set_value(900);

    colorizer->add_stop(stop);

    mapnik::put(raster_sym, mapnik::keys::colorizer, colorizer);
}
```

**Comment by am2222** [comment]
@talaj thanks for your help,
I have could solve my problem using your sample. But here I have another problem,
Here is my code

```c++
// raster dem
        feature_type_style dem;
        {
            rule r;
            {
                raster_symbolizer raster_sym;
		//colorizer
				mapnik::raster_colorizer_ptr cl = std::make_shared<mapnik::raster_colorizer>();
				colorizer_stop st;
				st.set_color(color(127, 200, 100,255));
				st.set_value(900);
				//st.set_mode(mod);
				//st.set_mode_enum(mapnik::colorizer_mode_enum::COLORIZER_DISCRETE);
				cl->add_stop(st);
			 

				colorizer_stop st1;
				st1.set_color(color(127, 200, 20));
				st1.set_value(1500);
				//st.set_mode(mod);
				//st.set_mode_enum(mapnik::colorizer_mode_enum::COLORIZER_DISCRETE);
				cl->add_stop(st1);


				colorizer_stop st2;
				st2.set_color(color(127, 200, 60));
				st2.set_value(2500);
				//st.set_mode(mod);
				//st.set_mode_enum(mapnik::colorizer_mode_enum::COLORIZER_DISCRETE);
				cl->add_stop(st2);

		put(raster_sym, mapnik::keys::colorizer, cl);
                //put(raster_sym,keys::opacity,"1");
                put(raster_sym,keys::scaling,"bilinear");
                put(raster_sym,keys::mode,"normal");
                r.append(std::move(raster_sym));
            }
            dem.add_rule(std::move(r));
        }

        m.insert_style("dem", std::move(dem));
```

Here is my layer
```c++
//raster
		{
			parameters p;
			p["type"]="gdal";
			p["file"]="../../demo/data/dem.tif";
			layer lyr("dem");
			lyr.set_datasource(datasource_cache::instance().create(p));
        		lyr.add_style("dem"); // in style.xml
        		m.add_layer(lyr);

		}
```

The result should be a map with three main colors. right?But mapnik only draws rasters border nothing else. Where am I doing wrong?

**Comment by talaj** [comment]
Those colors are very similar and hard to distinguish. I tried it on [this raster](https://github.com/mapnik/test-data/blob/master/raster/dataraster.tif) with this code:

```c++

#include <mapnik/map.hpp>
#include <mapnik/layer.hpp>
#include <mapnik/datasource_cache.hpp>
#include <mapnik/raster_colorizer.hpp>
#include <mapnik/symbolizer.hpp>
#include <mapnik/symbolizer_utils.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/image_util.hpp>

void mk_style_dem(mapnik::Map & map)
{
    //colorizer
    mapnik::raster_colorizer_ptr cl = std::make_shared<mapnik::raster_colorizer>();
    mapnik::colorizer_stop st;
    st.set_color(mapnik::color(255, 0, 0));
    st.set_value(0);
    //st.set_mode(mod);
    //st.set_mode_enum(mapnik::colorizer_mode_enum::COLORIZER_DISCRETE);
    cl->add_stop(st);

    mapnik::colorizer_stop st1;
    st1.set_color(mapnik::color(0, 255, 0));
    st1.set_value(10);
    //st.set_mode(mod);
    //st.set_mode_enum(mapnik::colorizer_mode_enum::COLORIZER_DISCRETE);
    cl->add_stop(st1);

    mapnik::colorizer_stop st2;
    st2.set_color(mapnik::color(0, 0, 255));
    st2.set_value(25);
    //st.set_mode(mod);
    //st.set_mode_enum(mapnik::colorizer_mode_enum::COLORIZER_DISCRETE);
    cl->add_stop(st2);

    mapnik::raster_symbolizer raster_sym;
    mapnik::put(raster_sym, mapnik::keys::colorizer, cl);
    //put(raster_sym,keys::opacity,"1");
    mapnik::put(raster_sym, mapnik::keys::scaling, mapnik::scaling_method_e::SCALING_BILINEAR);
    mapnik::put(raster_sym, mapnik::keys::mode, mapnik::colorizer_mode_enum::COLORIZER_LINEAR);

    mapnik::feature_type_style dem;
    mapnik::rule r;
    r.append(std::move(raster_sym));
    dem.add_rule(std::move(r));

    map.insert_style("dem", std::move(dem));
}

void mk_layer_dem(mapnik::Map & map)
{
    mapnik::parameters p;
    p["type"] = "gdal";
    p["file"] = "dataraster.tif";
    p["band"] = 1;
    mapnik::layer lyr("dem", "+init=epsg:32630");
    lyr.set_datasource(mapnik::datasource_cache::instance().create(p));
    lyr.add_style("dem"); // in style.xml
    map.add_layer(lyr);
}

main()
{
    mapnik::datasource_cache::instance().register_datasources("/home/talaj/dev/mapnik/plugins/input");

    mapnik::Map map(512, 512);

    mk_style_dem(map);
    mk_layer_dem(map);

    map.zoom_all();

    mapnik::image_rgba8 image(map.width(), map.height());
    mapnik::agg_renderer<mapnik::image_rgba8> ren(map, image, 1);
    ren.apply();

    mapnik::save_to_file(image, "map.png", "png32");
}
```

And the result with original stop colors is this:
![map0](https://user-images.githubusercontent.com/1950911/28091641-f344dabc-6690-11e7-9822-b6d2d14ace1f.png)

After changing stop colors to red, green, blue:
![map](https://user-images.githubusercontent.com/1950911/28091669-0b7c4782-6691-11e7-9cbf-bbacf31c0530.png)

**Comment by am2222** [comment]
@talaj  thanks very much for your time,
I could render my map very well, but while I want to use opacity my layer disappears. Here is my example
```

`#include <mapnik/map.hpp>
#include <mapnik/layer.hpp>
#include <mapnik/datasource_cache.hpp>
#include <mapnik/raster_colorizer.hpp>
#include <mapnik/symbolizer.hpp>
#include <mapnik/symbolizer_utils.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/image_util.hpp>

void mk_style_dem(mapnik::Map & map)
{
    //colorizer
    mapnik::raster_colorizer_ptr cl = std::make_shared<mapnik::raster_colorizer>();
    mapnik::colorizer_stop st00;
    st00.set_color(mapnik::color(73, 193, 54));
    st00.set_value(0);
    cl->add_stop(st00);

    mapnik::colorizer_stop st0;
    st0.set_color(mapnik::color(110, 220, 110));
    st0.set_value(1200);
    cl->add_stop(st0);

    mapnik::colorizer_stop st;
    st.set_color(mapnik::color(240, 250, 160));
    st.set_value(1500);
    cl->add_stop(st);

    mapnik::colorizer_stop st1;
    st1.set_color(mapnik::color(230, 220, 170));
    st1.set_value(2000);
    cl->add_stop(st1);

    mapnik::colorizer_stop st2;
    st2.set_color(mapnik::color(220, 220, 220));
    st2.set_value(2200);
    cl->add_stop(st2);

    mapnik::colorizer_stop st3;
    st3.set_color(mapnik::color(250, 250, 250));
    st3.set_value(2500);
    cl->add_stop(st3);

    mapnik::raster_symbolizer raster_sym;
    mapnik::put(raster_sym, mapnik::keys::colorizer, cl);
   // mapnik::put(raster_sym, mapnik::keys::scaling, "fast");
    mapnik::put(raster_sym, mapnik::keys::mode, "normal");

    mapnik::feature_type_style dem;
    mapnik::rule r;
    r.append(std::move(raster_sym));
    dem.add_rule(std::move(r));

    map.insert_style("dem", std::move(dem));

	//start hillshade style

  mapnik::raster_colorizer_ptr cl2 = std::make_shared<mapnik::raster_colorizer>();
  mapnik::colorizer_stop h_st;
  h_st.set_color(mapnik::color(0, 0, 0));
  h_st.set_value(0);
  cl2->add_stop(h_st);

  mapnik::colorizer_stop h_st0;
  h_st0.set_color(mapnik::color(255, 255, 255));
  h_st0.set_value(200);
  cl2->add_stop(h_st0);
    mapnik::raster_symbolizer raster_sym_hilshade;
    mapnik::put(raster_sym_hilshade, mapnik::keys::colorizer, cl2);
    mapnik::put(raster_sym_hilshade, mapnik::keys::mode, "normal");
    mapnik::put(raster_sym_hilshade, mapnik::keys::opacity, "0.2");
    mapnik::feature_type_style hillshde;
    mapnik::rule rul;
    rul.append(std::move(raster_sym_hilshade));
    hillshde.add_rule(std::move(rul));

    map.insert_style("hilshade", std::move(hillshde));

}

void mk_layer_dem(mapnik::Map & map)
{


    mapnik::parameters p;
    p["type"] = "gdal";
    p["file"] = "dem.tif";
    p["band"] = 1.0;
    p["nodata"] = 32767.0;
    mapnik::layer lyr("dem","+proj=longlat +datum=WGS84 +no_defs");
    lyr.set_datasource(mapnik::datasource_cache::instance().create(p));
    lyr.add_style("dem"); // in style.xml
    map.add_layer(lyr);


        mapnik::parameters p1;
        p1["type"] = "gdal";
        p1["file"] = "dem_45.tif";
        p1["band"] = 1.0;
        p1["nodata"] = 0.0;
        mapnik::layer lyr1("hillshade","+proj=longlat +datum=WGS84 +no_defs");
        lyr1.set_datasource(mapnik::datasource_cache::instance().create(p1));
        lyr1.add_style("hilshade"); // in style.xml
        map.add_layer(lyr1);

}

int main()
{
    mapnik::datasource_cache::instance().register_datasources("/home/m/mapnik-3.x/plugins/input");

    mapnik::Map map(512, 512);

    mk_style_dem(map);
    mk_layer_dem(map);

    map.zoom_all();

    mapnik::image_rgba8 image(map.width(), map.height());
    mapnik::agg_renderer<mapnik::image_rgba8> ren(map, image, 1);
    ren.apply();

    mapnik::save_to_file(image, "map.png", "png32");
return 0;
}`

```
it seems raster layers has sth wrong with opacity. I can render this map without setting opacity and hillshade layer renders well but adding opacity causes hillsahde layer disappears.

**Comment by talaj** [comment]
```c++
mapnik::put(raster_sym_hilshade, mapnik::keys::opacity, "0.2");
```
The value should not be string, but double:
```c++
mapnik::put(raster_sym_hilshade, mapnik::keys::opacity, 0.2);
```
There was also mistake in my example. Scaling and mode should be set like this:

```c++
mapnik::put(raster_sym, mapnik::keys::scaling, mapnik::scaling_method_e::SCALING_BILINEAR);
mapnik::put(raster_sym, mapnik::keys::mode, mapnik::colorizer_mode_enum::COLORIZER_LINEAR);
```

**Comment by talaj** [comment]
If you want to use string values, you must parse them with [`mapnik::parse_expression()`](https://github.com/mapycz/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/expression.hpp#L44) this way:

```c++
mapnik::put(raster_sym, mapnik::keys::opacity, mapnik::parse_expression("0.5"));
```

The output type of `mapnik::parse_expression()` is `mapnik::expression_ptr`:
```c++
mapnik::expression_ptr opacity = mapnik::parse_expression("0.5");
mapnik::put(raster_sym, mapnik::keys::opacity, opacity);
```

**Comment by am2222** [comment]
@talaj  thanks very much for your help. My problem solved now.
